### ISSUE TITLE
Unexpected Termination

### ISSUE THREAD

**Issue by wfjsw** [TelegramMessenger/MTProxy#1]
Got terminated immediately after started.

Log: 
```
***mtproto-proxy -u nobody -p *** -H *** -S *** --aes-pwd proxy-sec
et proxy-multi.conf -M 1
[12974][2018-05-30 22:27:35.054276 local] Invoking engine mtproxy-
.01 compiled at May 30 2018 22:18:16 by gcc 6.3.0 20170516 64-bit
fter commit 2fd27cb0753c62e5766c86db28f2acc1d755547f
[12974][2018-05-30 22:27:35.054718 local] config_filename = 'proxy
multi.conf'
[12974][2018-05-30 22:27:35.055146 local] creating 1 workers
[12974][2018-05-30 22:27:35.058921 local] Started as [10.243.233.9
:2094:12974:1527690455]
[12974][2018-05-30 22:27:35.059232 local] configuration file proxy
multi.conf re-read successfully (797 bytes parsed), new configuration active
[12974][2018-05-30 22:27:35.059318 local] main loop
[12975][2018-05-30 22:27:35.059437 local] Started as [10.243.233.9
:2094:12975:1527690455]
[12975][2018-05-30 22:27:35.060119 local] configuration file proxy
multi.conf re-read successfully (797 bytes parsed), new configuration active
[12975][2018-05-30 22:27:35.060322 local] main loop
[12974][2018-05-30 22:27:36.004512 local] Child 12975 terminated, aborting
```

**Comment by wfjsw** [comment]
Died as soon as a connection is made, not on started.

**Comment by LDVSOFT** [comment]
I have manually specified public adrress, still crashes on first client.

**Comment by wfjsw** [comment]
I swapped -p and -H then it works(sort of)

**Comment by p1ratrulezzz** [comment]
Haha, yes there is a confusing thing about it. -H is the address which actually used to listen for incoming connections (the port you put in the port field on telegram client) and -p used for something internal. On many servers if you have nginx or any web server set up already with https you can't set it to 443 as it will be already binded by nginx or apache. Just start it with something like -H 6889

**Comment by LDVSOFT** [comment]
@p1ratrulezzz Crashes for me on unoccupied unpriviledged port, though!

**Comment by wfjsw** [comment]
@p1ratrulezzz no both two port is not occupied.
gdb didn't show anything helpful.

**Comment by stanislavvv** [comment]
Confirm crash at start under Debian 9 (gcc 6.3).
It is not "Address already in use" error.

**Comment by wfjsw** [comment]
Well, I found the code is highly targeted on Intel while I am using AMD...

**Comment by stanislavvv** [comment]
I build on desktop and use virtualized cpu on target. How i can switch off any cpu type locks?

**Comment by wfjsw** [comment]
I think crc32.c and crc32c.c are the biggest hells.

**Comment by coolermister** [comment]
Have the same)

**Comment by stek29** [comment]
@wfjsw @stanislavvv does it work if you pass `--crc32c` ?

**Comment by wfjsw** [comment]
@stek29 nop crc32c also use weird builtin functiond thus same results.

**Comment by stanislavvv** [comment]
same result with `--crc32c`

**Comment by stanislavvv** [comment]
Sorry, forgot `git pull` and `make clean && make`
Now it's work.

**Comment by wfjsw** [comment]
🤔 I still have it. weird

**Comment by wfjsw** [comment]
```
Thread 1 "mtproto-proxy" received signal SIGILL, Illegal instruction.
0x000055555557251e in update_thread_stat ()
(gdb) bt
#0  0x000055555557251e in update_thread_stat ()
#1  0x000055555557259f in update_all_thread_stats ()
#2  0x00005555555997f9 in update_job_stats_gw ()
#3  0x000055555557590b in do_timer_job ()
#4  0x000055555557338b in unlock_job ()
#5  0x0000555555573c11 in job_timer_wakeup_gateway ()
#6  0x0000555555580911 in thread_run_timers ()
#7  0x000055555557803a in epoll_work ()
#8  0x000055555559a67d in default_engine_server_start ()
#9  0x000055555559ad13 in default_main ()
#10 0x00007ffff6c842e1 in __libc_start_main (main=0x555555564ff0 <main>, argc=15,
    argv=0x7fffffffe3d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffe3c8) at ../csu/libc-start.c:291
#11 0x000055555556520a in _start ()
```
🤔Threads?

**Comment by wfjsw** [comment]
remove -O3, changed march it finally runs :/
well I run it with proxychains and seems no connection is made through my tunnel.

**Comment by stek29** [comment]
@wfjsw wasn't just removing the march enough?

**Comment by wfjsw** [comment]
@stek29 didn't remove march but changed it to native

**Comment by coolermister** [comment]
Confirm @wfjsw. Changed march to native, O3 to O2, and it works)
