### ISSUE TITLE
License and Copyright clarifications

### ISSUE THREAD

**Issue by omkarnathsingh** [TelegramMessenger/MTProxy#10]
Copyright year in code is expired already, and two license applies, which one to consider and under which year?

**Comment by stek29** [comment]
Most files specify used license in the header.
Also, what you’re referring to aa copyright year might just be years on which modifications to that file were done (and by whom). It’s pretty common to leave year and name when file is edited in big projects — have a look at some of Aaple Open Source projects for example.

**Comment by omkarnathsingh** [comment]
Thanks for clarifications. I felt it should all be updated to 2018.
