### ISSUE TITLE
 bash: ./mtproto-proxy: No such file or directory

### ISSUE THREAD

**Issue by telegramopennetwork** [TelegramMessenger/MTProxy#103]
hi
whene i send "
./mtproto-proxy -u nobody -p 8888 -H 443 -S <secret> --aes-pwd proxy-secret proxy-multi.conf -M 1

see this error : 
bash: ./mtproto-proxy: No such file or directory 

Help me please

**Comment by telegramopennetwork** [comment]
i installed  build-essential   libssl-dev   zlib1g-dev   ...but again this error see : 
  bash: ./mtproto-proxy: No such file or directory
...


any body can help me??

**Comment by Katarn** [comment]
> To build, simply run `make`. Your binary will be in `objs/bin/mtproto-proxy`

Run `cd objs/bin` before `./mtproto-proxy`.
Or `objs/bin/mtproto-proxy`.

**Comment by telegramopennetwork** [comment]
how oi can compile vinary with "make" commond?!
whene i type "make" error : 

make: *** No targets specified and no makefile found.  Stop.

**Comment by Katarn** [comment]
Try to run `./configure` before `make`.

**Comment by stek29** [comment]
@Katarn there's no `configure` in MTProxy, it doesn't use autotools.

**Comment by stek29** [comment]
@telegramopennetwork Please follow instructions carefully.
