### ISSUE TITLE
Doesn't load images

### ISSUE THREAD

**Issue by denisemenov** [TelegramMessenger/MTProxy#105]
I have 1 fresh and clean vds with mtproxy in Germany. It's not blocked in Russia.
Messages works well, but images not. All links previews, stickers and sent images are not downloaded. 
Socks5 (dante) on the same server works without this problem.

______________
Арендовал vds в Германии (CentOS 7), поставил mtproxy, обновил все пакеты и прокси листы, перезагрузил 200 раз. Работает всё, кроме картинок. Картинки не грузятся совсем: превью ссылок, новые стикеры, отправленные фотографии. 
Ставлю на тот же сервер dante proxy - работает без косяков с картинками.

**Comment by seega** [comment]
@denisemenov Yota somehow blocks all files via mtproto (maybe other operators too).

**Comment by loskiq** [comment]
@denisemenov I rent VPS by Amazon and Microsoft Azure and everything works

**Comment by denisemenov** [comment]
@seega I have Megafon. I know that it's the same shit, but with Yota i had a lot of problems on shared internet (torrents, cloud storage, speed) few years ago and went to Megafon, which works better.
@loskiq i had this issue on Hetzner. 

I'll try other operators and vds later. Thanks.

**Comment by LibertyPaul** [comment]
@denisemenov this is strange, I have VPS in Hetzner with both MTProxy and SOCKS, both work quite well  through Yota. A minute ago I was able to scroll down a channel with pics and videos and had no issues with that.

**Comment by vanoc** [comment]
Same. Yota.

**Comment by denisemenov** [comment]
https://t.me/rknapocalypsetime/108

**Comment by iqdoctor** [comment]
i use ubuntu 18 on vultr.com and digitalocean.com - all is ok.

**Comment by seega** [comment]
@iqdoctor through Yota and ios/android TG app?

**Comment by NexonSU** [comment]
Same issue with Yota, even with another port.
When I turn off proxy, it works, but very slow.
When I use VPN to the same server, it works.
When I use any another public proxy, it works.

**Comment by jamesfirstv** [comment]
Я встречал такое раньше. Если:
1) в локальной сети существуют две машины (например, телефон, раздающий вайфай и ноутбук на вайфае)
2) на телефоне запущен VPN и Телеграм работает через него, но сломан маршрут от ноутбука до интернета, так как VPN на телефоне запущен после подключения ноутбука к вайфаю, то есть после получения настроек от телефонного DHCP
3) на ноутбуке Телеграм работал без прокси и впн хорошо, но после старта впна перестаёт передавать любой медиа контент, только текст, то есть сообщения и техническую информацию 

Складывается впечатление о наличии проксирования текстового трафика через любое приложение Телеграма в локальной сети

**Comment by exhang** [comment]
Решения этой проблемы в данный момент не найдено?

**Comment by NexonSU** [comment]
@exhang опытным путем было установлено, что йота режет mtproto трафик.

**Comment by Kooroshya** [comment]
i have same issue , any idea ?

**Comment by exhang** [comment]
> i have same issue , any idea ?

Use socks5 proxy.

**Comment by amirhgh** [comment]
> i use ubuntu 18 on vultr.com and digitalocean.com - all is ok.

I am using Vultr and have the same issue

**Comment by nimatrueway** [comment]
It's been almost ~ 2 weeks that we have the same problem in Iran with MTProto proxies. Texts are communicated fine, but any non-text data (image/video/..) communication are painfully slow. This is not the case when we use VPNs to access telegram (like Cisco Open-Connect).

**Comment by NexonSU** [comment]
@nimatrueway Yep, seems like it's ISP fault. We need to "encapsulate" our MTProto traffic over... something. I don't know.

**Comment by lesha-co** [comment]
@NexonSU what is the point of it then? I thought that mtproto should be "pretending to be https so isps can't track it". Today they can block (parts of) MTProto, tomorrow they just ban all socks traffic because it's easily recognizable. Oh and socks proxy passwords aren't secured in any way so they can just sniff them.

**Comment by exhang** [comment]
> @NexonSU what is the point of it then? I thought that mtproto should be "pretending to be https so isps can't track it". Today they can block (parts of) MTProto, tomorrow they just ban all socks traffic because it's easily recognizable. Oh and socks proxy passwords aren't secured in any way so they can just sniff them to check if that's really a telegram proxy you're connecting to.

Yes, Russan ISP "Yota" sniff MTProto traffic, i use only socks5.

**Comment by russianxiii** [comment]
Now images are loaded through MTProto and Yota.

**Comment by exhang** [comment]
> Now images are loaded through MTProto and Yota.

No.

**Comment by d0tfile** [comment]
@exhang did you try random padding mode?

**Comment by exhang** [comment]
> @exhang did you try random padding mode?

Yes, i on padding mode.

**Comment by rusinv** [comment]
Have similar issue with Yota.

**Comment by onikethem** [comment]
🤔

در چهارشنبه ۳۰ ژانویهٔ ۲۰۱۹،‏ ۲۳:۳۱ Valery Rusin <notifications@github.com
نوشت:

**Comment by ekifox** [comment]
Same shit on Yota with mtproto, socks5 works fine.

**Comment by RistiCore** [comment]
Yota marks all unrecognized traffic as "p2p" and shape it as torrent-traffic — 32 Kbps. The same problem with Wireguard VPN for example: Yota cannot recognize its UDP noise-like traffic like any known service and shrink througput to 32 Kbps.

**Comment by onikethem** [comment]
☕

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۴:۱۲ RistiCore <notifications@github.com نوشت:

**Comment by NexonSU** [comment]
@RistiCore thx, finally someone explained this issue.

**Comment by onikethem** [comment]
😍😍😍😍😍😍😍😍

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۴:۲۵ Nexon <notifications@github.com نوشت:

**Comment by onikethem** [comment]
Do you have a telegram channel?

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۴:۲۵ Nexon <notifications@github.com نوشت:

**Comment by onikethem** [comment]
I am investing. Anyone have a telegram channel to share my proxy links. I
can pay a paycheck 1 bitcoin

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۴:۲۸ Mohammad Hossini <hossini081@gmail.com نوشت:

**Comment by ekifox** [comment]
Socks5 on tcp/443 is normal on Yota.

**Comment by L11R** [comment]
@denisemenov @ekifox @RistiCore I found the solution. Yota guarantees that they don't shape traffic at 1194 and 51820 ports. I checked and it works. WireGuard also works flawlessly.

**Comment by NexonSU** [comment]
@L11R That's why OpenVPN working well :D

**Comment by L11R** [comment]
@stek29 I guess it could be closed now.

**Comment by onikethem** [comment]
So right

در جمعه ۸ فوریهٔ ۲۰۱۹،‏ ۱۷:۵۶ Savely Krasovsky <notifications@github.com
نوشت:

**Comment by denisemenov** [comment]
> @denisemenov @ekifox @RistiCore I found the solution. Yota guarantees that they don't shape traffic at 1194 and 51820 ports. I checked and it works. WireGuard also works flawlessly.

Maybe it helps with Yota, but not with Megafon. I tried to use 51820 and media still doesn't load.
I do not think that it is normal when we should be limited to use only 1 or 2 ports. For example, there are situations when we cannot use port 1194 because it is already busy.

@stek29 please, open it back.

**Comment by denisemenov** [comment]
I tried to use firewalld instead of iptables on Centos 7 and the images have been loaded.  🤷‍♂️

**Comment by L11R** [comment]
@denisemenov how using firewalld instead of iptables can cause image loading problems on specific ISP? 🤔

**Comment by denisemenov** [comment]
I wrote that I have problems not on Yota, but on Megaphone (and Tele2). I also wrote that this problem does not disappear after changing the port. So I was not in favor of the fact that the problem is in a particular provider.

**Comment by Nill-R** [comment]
> @denisemenov @ekifox @RistiCore I found the solution. Yota guarantees that they don't shape traffic at 1194 and 51820 ports. I checked and it works. WireGuard also works flawlessly.

No :( I have trouble on Yota with Wireguard at 51820 and with MTProto on any ports. 
Now I configured my WireGuard for 1194/udp and all is ok. Yota shapping all unknown traffic. I think tomorrow I'll reconfigure one of my MTProto Proxy for 1194 :) Yota is very bad choice

**Comment by Nill-R** [comment]
> I tried to use firewalld instead of iptables on Centos 7 and the images have been loaded. 🤷‍♂️

But firewalld is user-backend for iptables ;)

**Comment by lucidyan** [comment]
@stek29 I don't understand why this problem is closed. 

First, I think not only YOTA reduces traffic in this way. Other ISP's can do it too.

Secondly, it is a serious vulnerability in the MTProxy that in case of the introduction of something like white lists, completely blocks it.

Are there any plans for mimic other protocols?

**Comment by L11R** [comment]
@lucidyan vulnerability? C'mon, Yota just shapes traffic with unknown signature. Telegram cannot fix it. Don't use Yota, change ISP.

**Comment by lucidyan** [comment]
@L11R This is a protocol that is designed with only target: to circumvent ISP blocks. And if such traffic is so easy to detect and shape, in my opinion, it does not cope with its task. That is why I consider this a vulnerability issue in the first place.

E.g., tomorrow, the same ISP will start shaping traffic on all ports and then this tool will simply become useless. And there will not be workaround at all, except use some kind of tunnels for all trafiic: but for the large amount of users it will be unacceptable and hard.

**Comment by L11R** [comment]
@lucidyan Yota doesn't detect type of traffic. It just shapes everything unknown. So it's not vulnerability.

If tomorrow ISP will shape traffic on all ports... Well sorry for you shitty ISP, because you will be also unable to use OpenVPN/WireGuard/IKEv2/anything else. There is no out of the box solution if you ISP is fucking crazy.

**Comment by lucidyan** [comment]
@L11R I have the OpenVPN server, running at the same machine, at the non-standard port and Yota doesn't shape it at all. 
So I'm going to disagree with you.

P.S.
Mad ISP's is not such a problem, as mad laws.

**Comment by L11R** [comment]
@lucidyan Well, maybe they whitelisted it since a while. Because OpenVPN worked well for me only at 1194. 

Anyway your proposal requires client modification. Even if you wrap MTProxy traffic into HTTPS or sorta.

**Comment by lucidyan** [comment]
@L11R So if some ISP can whitelist/blacklist some kind of traffic it's lead us to china scenario. Sad but true.

And of course it requires client modification, but developers the same. And I guess they should think about mimicking, if they are concerned about their users, in the future.

**Comment by L11R** [comment]
@lucidyan in case of Russia you are still free of choice. There are a bunch of other ISP's who doesn't do anything like this.

**Comment by yukpun** [comment]
If somebody still looking for solution, here it is:
Change port for MTProto to 1194 or 51820. I changed to 51820 and now it works fine with Yota.

Took this solution here - https://toster.ru/q/597580

**Comment by denisemenov** [comment]
> If somebody still looking for solution, here it is:
> Change port for MTProto to 1194 or 51820. I changed to 51820 and now it works fine with Yota.
> 
> Took this solution here - https://toster.ru/q/597580

https://github.com/TelegramMessenger/MTProxy/issues/105#issuecomment-461016989

**Comment by ownmas** [comment]
Russian ISP "YOTA" learn how to detect all Fake TLS proxies and now reduce their speed to 64 kbps.

Also, they reduce proxies speed on 1194 and 51820 ports now too.

**Comment by L11R** [comment]
@ownmas are you using Fake TLS variant at 443? If not, no matter what protocol you are using, they will always reduce speeds. I switched to Tele2 and have not any problems at any port.

**Comment by ownmas** [comment]
> @ownmas are you using Fake TLS variant at 443? If not, no matter what protocol you are using, they will always reduce speeds. I switched to Tele2 and have not any problems at any port.

I tried using different ports, 443, 1194 and 51820. All reduces speed.

**Comment by lucidyan** [comment]
@ownmas Tried [this Fake TLS implementation](https://github.com/alexbers/mtprotoproxy) on different ports - works well only at 443, but other ports was shaped by YOTA.

Check out that implementation, maybe you make it work.

**Comment by Nill-R** [comment]
@lucidyan Fake TLS and normal mtproto proxy with dd in key work well at 1194/tcp and Yota. I have two proxies with 1194/tcp and use Yota as main number.

**Comment by RistiCore** [comment]
Yota reduces speed of all unrecognized traffic as p2p-traffic (32 Kbps). On all ports except some Yota reduces speed at the beginning. On ports 1194, 443 and 51820 Yota allows full-speed througput for some time and then reduce it too.

The best solution is not to use Yota.

**Comment by Ghoreish** [comment]
If you can't download images or videos or GIFs or... you should use official Official Script.
curl -o MTProtoProxyOfficialInstall.sh -L https://git.io/fjo3u && bash MTProtoProxyOfficialInstall.sh
use this and install your proxy with 1 worker
