### ISSUE TITLE
Faild to start proxy 

### ISSUE THREAD

**Issue by rozbeh98** [TelegramMessenger/MTProxy#107]
hi 
i run proxy at first time is good but problem with services 

Jun 08 15:09:51 sweeti mtproto-proxy[3443]:         --nat-info <arg>                           <local-addr>:<global-addr>        sets network address translation for RPC protocol handshake
Jun 08 15:09:51 sweeti mtproto-proxy[3443]:         --address <arg>                            tries to bind socket only to specified address
systemd[1]: Started MTProxy.
 systemd[1]: MTProxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: MTProxy.service: Unit entered failed state.
systemd[1]: MTProxy.service: Failed with result 'exit-code'.
 systemd[1]: MTProxy.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped MTProxy.
systemd[1]: MTProxy.service: Start request repeated too quickly.
 systemd[1]: Failed to start MTProxy.

**Comment by stek29** [comment]
Could you please show exact params specified in the unit file?

**Comment by rozbeh98** [comment]
i solve my problem  @stek29   i forget add proxy-****.conf line  to MTProxy.service 
:)

**Comment by alirezashahrokhi** [comment]
how do you add proxy-****.conf line to MTProxy.service?

**Comment by rozbeh98** [comment]
@alirezashahrokhi  flow the instruction its simple whats ur problem ?

**Comment by Eftekhar** [comment]
> ● MTProxy.service - MTProxy
>    Loaded: loaded (/etc/systemd/system/MTProxy.service; enabled; vendor preset: disabled)
>    Active: failed (Result: start-limit) since Fri 2018-06-22 16:01:23 EDT; 10min ago
>  Main PID: 26192 (code=exited, status=200/CHDIR)
> 
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: MTProxy.service: main process exited, code=exited, status=200/CHDIR
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: Unit MTProxy.service entered failed state.
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: MTProxy.service failed.
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: MTProxy.service holdoff time over, scheduling restart.
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: start request repeated too quickly for MTProxy.service
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: Failed to start MTProxy.
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: Unit MTProxy.service entered failed state.
> Jun 22 16:01:23 static.254.41.xxx.xxx.clients.your-server.de systemd[1]: MTProxy.service failed.
> 

please help me...

**Comment by stek29** [comment]
@Eftekhar show full log, with mtproxy output

**Comment by korangu** [comment]
make sure paths used in WorkingDirectory=   ExecStart=   are correct and accessible in service file.
