### ISSUE TITLE
Error while using make.

### ISSUE THREAD

**Issue by rezavn** [TelegramMessenger/MTProxy#109]
Hi
i keep facing with this error every time that i want to use make.
`make
cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"71814794c39e76fc75aaba931ef42da4d76b4461\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
cc: error: unrecognized command line option ‘-mpclmul’
cc: error: unrecognized command line option ‘-mfpmath=sse’
cc: error: unrecognized command line option ‘-mssse3’
Makefile:86: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 1
`
i dont know why.

P.S: i had done this command.
apt-get install libssl-dev zlib1g-dev build-essential

**Comment by stek29** [comment]
Are you building on x86?

**Comment by vitlav** [comment]
Sure, it is ARM.

**Comment by rezavn** [comment]
im kind of beginner.
is there any way that i can make it?

**Comment by rozbeh98** [comment]
my problem solved i forge add proxy-****.conf line to MTProxy.service file :)

**Comment by rezavn** [comment]
@rozbeh98
Will you contact me on Telegram?
@Rezavnn
