### ISSUE TITLE
mtproxy server behind cdn?

### ISSUE THREAD

**Issue by euphoria360** [TelegramMessenger/MTProxy#116]
Is it possible to hide our mtproxy servers behind Cloudflare or other cdns to hide its IP and decrease latency?

P.s I tried cloudflare but didnt work.

**Comment by smaznet** [comment]
cloudflare ports are limited

you should use one of this ports
80
8080
8880
2052
2082
2086
2095

**Comment by euphoria360** [comment]
I created a subdomain with cloudflare proxy enabled and also a MTProxy server on port 8880.
But when I tried to connect to my server, it rapidly connects/disconnects.

Do you have an already working setup?

**Comment by smaznet** [comment]
@euphoria360 

yes mine proxy works perfectly without disconnecting

**Comment by euphoria360** [comment]
@smaznet can i ask your port and any customized cloudflare settings (if any)?

**Comment by euphoria360** [comment]
And your port?

**Comment by smaznet** [comment]
80

**Comment by campoviy** [comment]
@smaznet Sorry, but in this case (when cloudflare icon in A record settings is grey) cloudflare is just DNS service, and IP is not hided. I'm right?

**Comment by euphoria360** [comment]
@smaznet. Yes, you are right. Grey means cloud proxy off. And its simply a dns management panel (which is still a very good one). The whole point of Cloudflare is it's CDN which is based on proxy.

And still, I can't run my MTPROXY server behind Cloudflare proxy.

**Comment by campoviy** [comment]
So, I don't think is possible to use cloudflare proxy, because it working only with http/s. MTProxy is not http/s.

**Comment by stek29** [comment]
It just makes no sense. even if it was possible, I doubt Cloudflare would be happy about that.

**Comment by euphoria360** [comment]
@stek29 why not!?
Telegram itself used similar method for Russia.

**Comment by stek29** [comment]
@euphoria360 because Cloudflare CDNs are not made just for proxying, but for caching too.
And afaik telegram did not use Cloudflare CDNs for russia

**Comment by iqdoctor** [comment]
You can install Cloudflare DNS client on your phone

Android: https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone

iOS: https://itunes.apple.com/us/app/1-1-1-1-faster-internet/id1423538627

It can help if your domain [not IP(!)] blocked by ISP DPI

See samples here: https://t.me/DigitalResistanceProxyChannel/2874

Telegram Desktop not needed 1.1.1.1, it has built-in secure resolver lib.

**Comment by onikethem** [comment]
Thanks
I love you 💗🌷💗🌷💗🌷💗🌷

در چهارشنبه ۳۰ ژانویهٔ ۲۰۱۹،‏ ۲۳:۲۹ DrProxyProSupport <
notifications@github.com نوشت:

**Comment by onikethem** [comment]
My channel
T.me/MTproto_iran
Plz help me
i'm from iran

در چهارشنبه ۳۰ ژانویهٔ ۲۰۱۹،‏ ۲۳:۳۸ Mohammad Hossini <hossini081@gmail.com
نوشت:
