### ISSUE TITLE
Other Port / NO 443 - help me force

### ISSUE THREAD

**Issue by telegramopennetwork** [TelegramMessenger/MTProxy#118]
hi 
443 por is banned in my server...can i use other ports??

**Comment by telegramopennetwork** [comment]
any body cant help me?!

**Comment by VahidPY** [comment]
@telegramopennetwork Yes, you can. Just try other ports like 8080,1080,etc.
Port needs to be open in your firewall.

Plz close the issue.

**Comment by telegramopennetwork** [comment]
@VahidPY firewall in ubuntu? i have ubuntu server. can you say all ports?

**Comment by VahidPY** [comment]
Yes, firewall of your server.
You can deny/allow ports by UFW. UFW is a command-line tool that you can simply add rules to your firewall.
For example to open port 1080: `sudo ufw allow 1080`

By the way, it's a basic concept in linux server management, so you should learn about it from other resources, this is a not good place for expanding this topic.
