### ISSUE TITLE
How can I make my MTProxy start automatically if a server restart is forced? 

### ISSUE THREAD

**Issue by Millidan** [TelegramMessenger/MTProxy#123]
Also got another question, what is a "worker" and how many do I need for a MTProxy used by maybe 50 people? 

Another problem is when I use this command: 
`./mtproto-proxy --help`
I get this error:
`-bash: ./mtproto-proxy: No such file or directory`

What is wrong here?

Thanks for the effort you put into this project 👍

**Comment by SatoshiNakamotoOfficial** [comment]
first you need change directory,
 cd /somedirectory/MTProxy/objs/bin, then use ./mtproto-proxy

**Comment by CraftedCat** [comment]
You can use install script, if Debian 9 https://github.com/CraftedCat/MTProxyInstallScript/

**Comment by iqdoctor** [comment]
RTFM: https://github.com/TelegramMessenger/MTProxy#systemd-example-configuration
