### ISSUE TITLE
Install Docker problem 

### ISSUE THREAD

**Issue by pouyaSamie** [TelegramMessenger/MTProxy#130]
Hi Everyone 
i know maybe it's not the best place to ask this question but i have issue installing docker server on my Debian 8
when i run : 

> `docker run -d -p443:443 --name=mtproto-proxy --restart=always -v proxy-config:/data telegrammessenger/proxy:latest`

it gave me an error : 

> "flag provided but not defined: -p443:443"

I tried -p 443:443 ( with a space it worked ) but i had another issue : 

> "Error response from daemon: cannot bind mount volume: proxy-config volume paths must be absolute"

I change the command to (replace proxy-config with /proxy-config) and also another port because my 443 port is in use: 

> docker run -d -p 1088:443 --name=mtproto-proxy --restart=always -v /proxy-config:/data telegrammessenger/proxy:latest 

it got installed but now my telegram client can not connect 

the docker is running and it is listening on port 1088 

where did i go wrong ?

**Comment by stek29** [comment]
No idea, sorry :(
