### ISSUE TITLE
UB and potential crypto problem in release builds

### ISSUE THREAD

**Issue by detunized** [TelegramMessenger/MTProxy#131]
I've been browsing different parts of the code at random. I stumbled upon this line here:

https://github.com/TelegramMessenger/MTProxy/blob/20824f5fa8af3939e667fba5c1785f02059c1c43/net/net-crypto-aes.c#L226

In release build this will be stripped and value of `T` is undefined. In release `assert` should be defined like this (see http://en.cppreference.com/w/cpp/error/assert):

```
#define assert(condition) ((void)0)
```

**Update:** Found more code like this here:

https://github.com/TelegramMessenger/MTProxy/blob/20824f5fa8af3939e667fba5c1785f02059c1c43/net/net-crypto-dh.c#L153

And there's more in that module. Unless there's a redefinition of `assert`, which would be confusing, this should not work in release.

**Comment by stek29** [comment]
it does work in release. you could've built it and looked at the binary, or scrolled through GitHub issues to see failing assert reports.
