### ISSUE TITLE
Images won't upload/download

### ISSUE THREAD

**Issue by pav5000** [TelegramMessenger/MTProxy#133]
I'm using the official docker image of mtproto proxy. Most of the time images cannot be uploaded or downloaded when Telegram is connected to mtproto proxy. When I switch to socks5 located at the same server, the issue resolves.

**Comment by niksergey** [comment]
The same behavior only via Yota, the other providers work well

**Comment by vanoc** [comment]
Same. Yota.

**Comment by nikkymen** [comment]
+ 1, with yota provider (Russia) media content not worked

**Comment by stek29** [comment]
#105

**Comment by Ghoreish** [comment]
If you can't download images or videos or GIFs or... you should use official Official Script.
curl -o MTProtoProxyOfficialInstall.sh -L https://git.io/fjo3u && bash MTProtoProxyOfficialInstall.sh
use this and install your proxy with 1 worker
