### ISSUE TITLE
add variable packet size

### ISSUE THREAD

**Issue by f242** [TelegramMessenger/MTProxy#135]
RKN successfully blocks MTProxy traffic by packet size
https://github.com/darkk/poormansmtproto/blob/master/nqtg.py
https://t.me/rknapocalypsetime/108

**Comment by stek29** [comment]
#35

**Comment by shadowlmd** [comment]
@stek29, after reading #35 I really doubt this is a dupe. This ticket (and also #138) is about blocking mtproxy traffic with a practical solution while #35 is just some unconfirmed assertions about proxies being _detected banned_. These are different although somewhat related issues. Please consider reopening this ticket.

**Comment by stek29** [comment]
@shadowlmd #35 is used as a meta-issue.
