### ISSUE TITLE
Proxy Sponsor in chats list

### ISSUE THREAD

**Issue by zZoMROT** [TelegramMessenger/MTProxy#136]
In case when user is not subscribed for a sponsor proxy channel it is pinned as a first in users channel list. When user subscribes for a sponsor channel it leaves the pinned position and loose the mark “proxy sponsor”. Does that correct behavior of the sponsor channel ?

According to common sense the sponsor channel should always be the top channel, as a thanks to them for opportunity to be online

**Comment by stek29** [comment]
feel free to suggest option which conforms to your common sense to telegram via twitter or in-app support.
