### ISSUE TITLE
How to easily block telegram and any mtproxy

### ISSUE THREAD

**Issue by pragus** [TelegramMessenger/MTProxy#138]
0. `sysctl -w net.core.bpf_jit_enable = 1`

1. ` modprobe ipip && ip link set tunl0 up`

2. `tcpdump -i tunl0 -ddd  'tcp and (ip[2:2]==157 or ip[2:2]==188) and tcp[tcpflags] & tcp-push != 0' | awk '{print $0","}' > tgram.bpf`

3.  ```iptables -A FORWARD -p tcp -m bpf --bytecode "`cat tgram.bpf`" -j DROP```

This is possible because of the fixed size of packets in mtproto.

**Comment by iShift** [comment]
One of Russia Government ISP (Rostelecom) tested MTPRoto bans with success result, so we need dynamic packet size

**Comment by iqdoctor** [comment]
https://github.com/darkk/poormansmtproto

**Comment by euphoria360** [comment]
#135

**Comment by stek29** [comment]
#35
