### ISSUE TITLE
Lack of MTPROTO proxy address provider channels

### ISSUE THREAD

**Issue by Big-Goal** [TelegramMessenger/MTProxy#14]
Some governments try to close MTPROTO proxy address provider channels. As a result **one of them with 400K members was closed** just today: t.me/ProxyMTProto
Moreover most of the people have difficulties obtaining the addresses of this type of proxy, also some of them _don't trust proxy provider channels_(you know because of security concerns).
 Please establish a MTPROTO proxy address provider official channel(with blue tick) and provide proxy server addresses to users.
The mechanism would be simple: proxy server owners will send their proxy info to a robot and after being analyzed automatically (do they work correctly or not), these addresses will be introduced in the official channel.

+The address of the official channel and robot could be sent through the official account of Telegram (in Telegram) to all of the users.

**Comment by stek29** [comment]
It has nothing to do with this repo.
Whole purpose of making an open source proxy server which can be hosted by anyone is to make proxies decentralized and harder to find & block.
If all proxies would be published in one channel/bot, it'd be really easy to block them.

**Comment by Big-Goal** [comment]
Got it. but at least telegram can explain about this type of proxy and how safe it is. Every day I see lots of people in the net asking:"how much can we trust the proxy providers? is it safe?" It's completely natural. Because most of the users are not IT experts but simple users who just want to communicate via a messaging app.
People have real concerns about what would happen if they use proxy servers provided by abusers. Telegram did tough 99 percent of the job but unfortunately not the accomplishing 1 percent, that is introducing MTProto proxy officially, describing how it works and how much it is secure(that the proxy owners have no way of deciphering the data) and to assure users their data would be safe even if the proxy server isn't safe.

**Comment by Big-Goal** [comment]
It's up to Telegram, but I wanna tell that if telegram don't provide clear descriptions this issue, unfortunately the efficiency/performance of this plan would be low, where as a batch of rumors is spread about this proxy everyday. 
You know the governments don't stand aside and say: OK let's watch how the proxy users increase day by day and our whole efforts to block telegram waste! one of the tricks the governments apply is Inducing insecurity or spreading rumors when there isn't official instructions or descriptions. As I told in my first comment, the government stopped one of the biggest mtproto proxy provider channels with 400K members(threatened the channel administrator who was inside the country). As a result rumors spread about the new type of proxy is unsafe(government detected the admin through their proxy servers / proxy provider channel is in hands of government etc.) then some people stopped using proxies and backed to VPNs(**which have some troubles but proved to be secure to the public!!**)

You can say anything in theory and I don't wanna argue but this is the reality in one of the telegram blocked countries you encounter with!

**Comment by Big-Goal** [comment]
It's up to Telegram, but I wanna tell that if telegram don't provide clear descriptions about this issue, unfortunately the efficiency/performance of this plan would be low, where as a batch of rumors is spread about this proxy everyday.
You know the governments don't stand aside and say: OK let's watch how the proxy users increase day by day and our whole efforts to block telegram waste! one of the tricks the governments apply is Inducing insecurity or spreading rumors when there isn't official instructions or descriptions. As I told in my first comment, the government stopped one of the biggest mtproto proxy provider channels with 400K members(threatened the channel administrator who was inside the country). As a result rumors spread about the new type of proxy is unsafe(government detected the admin through their proxy servers / proxy provider channel is in hands of government etc.) then some people stopped using proxies and backed to VPNs(which have some troubles but proved to be secure to the public!!)

You can say anything in theory and I don't wanna argue but this is the reality in one of the telegram blocked countries you encounter with!

**Comment by Big-Goal** [comment]
It's up to Telegram, but I wanna tell that if telegram don't provide clear descriptions about this issue, unfortunately the efficiency/performance of this plan would be low, where as a batch of rumors is spread about this proxy everyday.
You know the governments don't stand aside and say: OK let's watch how the proxy users increase day by day and our whole efforts to block telegram waste! one of the tricks the governments apply is _Inducing insecurity or spreading rumors_ when there isn't official instructions or descriptions. As I told in my first comment, the government stopped one of the biggest mtproto proxy provider channels with 400K members(threatened the channel administrator who was inside the country). As a result rumors spread about the new type of proxy is unsafe(government detected the admin through their proxy servers / proxy provider channel is in hands of government etc.) then some people stopped using proxies and backed to VPNs(**which have some troubles but proved to be secure to the public!!**)

You can say anything in theory and I don't wanna argue but this is the reality in one of the telegram blocked countries you encounter with!
I know the git hub is a place for codes not discussions, but I found nowhere to transmit this important issue. About the twitter accounts of telegram, I think the admins do no cares!

**Comment by Big-Goal** [comment]
It's up to Telegram, but I wanna tell that if telegram don't provide clear descriptions about this issue, unfortunately the efficiency/performance of this plan would be low, where as a batch of rumors is spread about this proxy everyday.
You know the governments don't stand aside and say: OK let's watch how the proxy users increase day by day and our whole efforts to block telegram waste! one of the tricks the governments apply is _Inducing insecurity or spreading rumors_ when there isn't official instructions or descriptions. As I told in my first comment, the government stopped one of the biggest mtproto proxy provider channels with 400K members(threatened the channel administrator who was inside the country). As a result rumors spread about the new type of proxy is unsafe(government detected the admin through their proxy servers / proxy provider channel is in hands of government etc.) then some people stopped using proxies and backed to VPNs(**which have some troubles but proved to be secure to the public!!**)

You can say anything in theory and I don't wanna argue but this is the reality in one of the telegram blocked countries you encounter with!
I know the git hub is a place for codes not discussions, but I found nowhere to transmit this important issue. About the twitter accounts of telegram, I think the admins do no care!

**Comment by mastermehrdad** [comment]
The Problem for the Proxy Providers is that their IP's will have a very short life as they will have to advertise their Proxies where ever they could, to cover the costs of their service through the sponsored Channels, but the more they advertise, the sooner they will be filtered. Hence, it is not worth the effort and/or investment to provide this service. on the other hand, for Telegram, each proxy will act as a node, regardless of its life cycle, therefore, the current situation is not a win win situation for both the Proxy Provider and Telegram, but rather a lose win situation !!
on the other hand, if the Proxies are distributed within the BlockChain and The Clients search for them automatically and use the nearest available one, as they do when looking for the closest Telegram Server, Not only they will become extremely hard to find by the filtering bodies, but also, making their life cycle much longer, therefore, making them, hopefully, profitable for the provider to invest and provide more proxies, which this in turn means there will be more nodes for Telegram to use. A Win Win Scenario.

**Comment by stek29** [comment]
> on the other hand, if the Proxies are distributed within the BlockChain and The Clients search for them automatically and use the nearest available one, as they do when looking for the closest Telegram Server, Not only they will become extremely hard to find by the filtering bodies

How does having all proxies in publicly available block chain structure make finding proxies hard for filtering bodies?
And what stops filtering bodies from just buying a bunch of phones, installing telegram on them and looking at the traffic, just like RKN likely does?

**Comment by mastermehrdad** [comment]
@stek29 
>  And what stops filtering bodies from just buying a bunch of phones, installing telegram on them and looking at the traffic, just like RKN likely does?

 I would have thought, having to buy phones !!? (how many!!?) is much harder compared to looking for them in Channels and Groups !!?
And isn't the data within the Block Chain, suppose to be Encrypted !!? 
The point is that the current situation will not last long and as soon as the Proxy Providers realize how fast their Proxies are blocked, not only they will **STOP** providing the community with new ones but also **STOP** their current ones.
