### ISSUE TITLE
delete MTProxy on server

### ISSUE THREAD

**Issue by mehran7880** [TelegramMessenger/MTProxy#142]
Hello.
I created one MTProxy on server. but i mistake on bot setting.
i want remove it and create another one.
when i want create one tells me already in use but created in first time
![capture](https://user-images.githubusercontent.com/16571690/41496270-b478c052-7150-11e8-9a3d-3f1b5fb6540d.PNG)

**Comment by kraleksandr** [comment]
`sudo killall mtproto-proxy`

**Comment by rockenren** [comment]
You already have something opened on port 443.
Check via netstat -plnt what do you have on port 443, then kill its process.
Then try to start mtproto-proxy again.
