### ISSUE TITLE
Sponsored channel is not shown if host IP representation is changed

### ISSUE THREAD

**Issue by ingria** [TelegramMessenger/MTProxy#147]
Example:

https://t.me/proxy?server=88.99.85.22&port=6985&secret=e11fb7c04ebd567a20ee6e095fe51116
https://t.me/proxy?server=013030652426&port=6985&secret=e11fb7c04ebd567a20ee6e095fe51116

These proxy links use same IP, but sponsored channel is shown only on the first one.

**Comment by ingria** [comment]
Also valid for hostname->ip:

https://t.me/proxy?server=drproxy.pro&port=443&secret=cf80d8084ac69d12d84992f2a96c84b2
vs
https://t.me/proxy?server=0x36263fe7&port=443&secret=cf80d8084ac69d12d84992f2a96c84b2

**Comment by stek29** [comment]
@ingria that's because client sends exact representation to the telegram servers, and it's a feature -- so same IP & same proxy can have different channels for different hostnames
