### ISSUE TITLE
it wont start -bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by pardismusic** [TelegramMessenger/MTProxy#148]
hi
is there any video for learning ? 

and can you say so easy to me what i should to do ? 
i have linux Debian 8 
and using putty ssh

just should copy all the ruls and pase and enter ?

how can i delete every thing  from it ?

**Comment by pardismusic** [comment]
its my root : 

root@dl:~/MTProxy/MTProxy/objs/bin#

its my problem ?

**Comment by stek29** [comment]
lack of basic *nix using skills is your problem
