### ISSUE TITLE
Error HTTP

### ISSUE THREAD

**Issue by Eftekhar** [TelegramMessenger/MTProxy#149]
Hello

I have problem with this command:
git clone https://github.com/TelegramMessenger/MTProxy

**Error:**

> Initialized empty Git repository in /root/MTProxy/.git/
> error:  while accessing https://github.com/TelegramMessenger/MTProxy/info/refs
> fatal: HTTP request failed
> 

CentOs: 6.7 Final Version

**Comment by kraleksandr** [comment]
Check your server' internet connection. Or you can use zip archive instead https://github.com/TelegramMessenger/MTProxy/archive/master.zip
