### ISSUE TITLE
How do I activate "Sponsored Channel" on my public proxy?

### ISSUE THREAD

**Issue by Millidan** [TelegramMessenger/MTProxy#151]
I have setup the official bot for my proxy and gave it the ID for the channel that I want but it's still not appearing. Do I have to enter something in my server's terminal? The bot gave me a tag starting with 3 dots too, But I'm not sure where to put that. Please help

**Comment by L11R** [comment]
@Millidan you should provide tag by param to mtproxy: `-P <YOUR TAG>`

**Comment by DJafari** [comment]
@Millidan first, before run your daemon, you must add your proxy in t.me/MTProxybot, after add, bot give a tag to you, next you must run daemon with given tag

**Comment by NabiKAZ** [comment]
**Attention:**
As I tested, If already joined to the sponsor channel, don't show the channel for you in top list.
