### ISSUE TITLE
How to stop the proxy?

### ISSUE THREAD

**Issue by peyman2afm** [TelegramMessenger/MTProxy#155]
Hi. I want to stop `mtproto-proxy` service but I can't stop it because when I try to stop it, it will be run again...
I tried to remove it but it's doesn't work too : (
Can anyone help me to stop this startup?
[Click here to see photo](http://s8.picofile.com/file/8330218476/bandicam_2018_06_26_20_13_45_054.jpg)

**Comment by aire1** [comment]
Type `systemctl stop MTProxy.service` and try again.

**Comment by alirezashahrokhi** [comment]
Just Type In SSH
service mtproto-proxy stop

**Comment by stek29** [comment]
@peyman2afm `systemctl disable MTProxy`
