### ISSUE TITLE
How To Hide Server IP From Other For None Blockable Server Idea?

### ISSUE THREAD

**Issue by alirezashahrokhi** [TelegramMessenger/MTProxy#157]
Hi
How To Hide Server IP From Other For None Blockable Server Idea? look Like Cloud fire Service?
Cloud fire Service Dont Support MTproto

**Comment by stek29** [comment]
it's not possible rn

**Comment by alirezashahrokhi** [comment]
Thanks For Replay
It s Possible we Use An Iranian Server For Traffic Forwarder To Other VPS for Hiding Second Server?

**Comment by stek29** [comment]
@alirezashahrokhi somewhat, but see #143. You'll probably have to play with --nat-info too.
