### ISSUE TITLE
Display different proxy sponsor for different secret on 1 VPS

### ISSUE THREAD

**Issue by denisemenov** [TelegramMessenger/MTProxy#161]
I have a VPS with 3 secret keys for different user groups:
- the first group without a proxy sponsor
- the second group with my personal channel
- the third group for a commercial project with its own channel

I thought that it can be used with multiple "-P", like it it used with multiple "-S", but Telegram always shows only one sponsored channel for all groups.
Is I need to use different VPS to display different channels for different groups, or did I do something wrong?

**Comment by stek29** [comment]
buy some domain, create different subdomains with same A records, and add proxies with those domains.

**Comment by denisemenov** [comment]
I already have different domains with subdomains, but it doesn't help me.

**Comment by sae13** [comment]
any solution?
just first p is working
