### ISSUE TITLE
Stats Problem

### ISSUE THREAD

**Issue by ea1234567** [TelegramMessenger/MTProxy#162]
MTProxy Bot never show me stats:

Sorry, we don't have stats for your proxy yet. Please come back later.

I changed port and secret key and tag but problem is remaining

I have another server and stats working fine
But in my new server i have stat problem

**Comment by ea1234567** [comment]
Problem solved automatically after 30 hours waiting

**Comment by Mehrabzabihi72** [comment]
سلام من بلد نیستم منظور github یعنی چی مغذرت
