### ISSUE TITLE
How to use adv in windows server

### ISSUE THREAD

**Issue by seqehr** [TelegramMessenger/MTProxy#165]
Hi
I used windows server for mtp
And i don’t know how to use sponser tag
And i can’t active adv
Please give me a solution, thanks

**Comment by stek29** [comment]
What windows server?

**Comment by seqehr** [comment]
2008 R2

**Comment by stek29** [comment]
I mean, what kind of mtproxy server are you using on windows?

**Comment by seqehr** [comment]
I used node js

**Comment by stek29** [comment]
Then why are you asking on this repo?
