### ISSUE TITLE
Don't work MTProto proxy server

### ISSUE THREAD

**Issue by MAPIIIAJI** [TelegramMessenger/MTProxy#166]
Firts, sorry for my English. I have a problem! I install mtproto on centos. I used this https://habrahabr.info/development/messaging-systems/2285-installing-mtproto-telegram-proxy-from-the-sources-on-centos-7.html and this https://github.com/TelegramMessenger/MTProxy  instuction for instalition. All installed successfully. Client listener port available. But if I connect to proxy it is not connent to it. I use next scheme: MTProxy <-NAT <-Internet <-Clients
                                                                                                   |------------------LAN--------|  |--------Inet---------| 

Execute command: /opt/MTProxy/objs/bin/mtproto-proxy -u mtproto -p 58888 -H 8888 -S ___
 --aes-pwd proxy-secret proxy-multi.conf -l /opt/MTT
Proxy/objs/log/mtproto.log -M 4 -P ___

Thank in advance.

**Comment by stek29** [comment]
what if you provide `--nat-info`?

**Comment by stek29** [comment]
Also, is the mtproxy server behind the nat, or are clients behind the nat?

**Comment by mr-mehti** [comment]
hi.
iranian can use this tutrial for make a [ MTPROTO Proxy](https://mehti.ir/%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d8%b3%d8%a7%d8%ae%d8%aa-%d9%be%d8%b1%d8%a7%da%a9%d8%b3%db%8c-%d8%aa%d9%84%da%af%d8%b1%d8%a7%d9%85-mtproto/)

**Comment by MAPIIIAJI** [comment]
Thanks for your reply! In the beginning, no. but after reading your message, added the option --nat-info, but this also did not help unfortunately

**Comment by MAPIIIAJI** [comment]
I have this scheme
MTProxy <-NAT <-Internet <-Clients
|------LAN------|    |--------Inet---------|

**Comment by MAPIIIAJI** [comment]
Thanks all, all is work perfect! Understood the problem

**Comment by stek29** [comment]
@MAPIIIAJI what was the issue?

**Comment by Mohammad-ipv6** [comment]
Issue Description: I would like to use the MTProto Proxy within a Linux server that is located behind the NAT. I can see that within your python script, by using ident.me, you replace the public IPv4 of the server running the docker file to server users' requests. However, my environment is different.

-     A home router has a WAN with public IP address as, for instance, 100.100.100.100

-     The Ubuntu server (running the MTProto docker image) has 192.168.1.1 (which obtains its address from the router via DHCP)

-     The ubuntu server has only two interfaces. lo and eth0: 192.168.1.1

-     The home router enabled the port forwarding to send the request received on the WAN port to the Ubuntu server on eth0.

Which parameters/line of code should be changed to cope with this case?

Expected solution: The working proxy with the server address for MTProto is 100.100.100.100
