### ISSUE TITLE
Ubuntu 17.10 (on Azure) core dumped

### ISSUE THREAD

**Issue by t0xa2000** [TelegramMessenger/MTProxy#168]
hi.
cannot start on Ubuntu

[90855][2018-07-11 21:01:55.359971 local] Invoking engine mtproxy-0.01 compiled at Jul 11 2018 21:00:15 by gcc 7.2.0 64-bit after commit 20824f5fa8af3939e667fba5c1785f02059c1c43
[90855][2018-07-11 21:01:55.360151 local] config_filename = 'proxy-multi.conf'
[90855][2018-07-11 21:01:55.360401 local] creating 1 workers
mtproto-proxy: common/pid.c:42: init_common_PID: Assertion `!(p & 0xffff0000)' failed.
[pid 90855] [time 1531332115]
------- Stack Backtrace -------
./mtproto-proxy(print_backtrace+0x2c)[0x5649db72f0fc]
./mtproto-proxy(extended_debug_handler+0x10)[0x5649db72f280]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13150)[0x7fd0361f7150]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fd035e3b0bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16d)[0x7fd035e3cf5d]
/lib/x86_64-linux-gnu/libc.so.6(+0x2ef17)[0x7fd035e32f17]
/lib/x86_64-linux-gnu/libc.so.6(+0x2efc2)[0x7fd035e32fc2]
./mtproto-proxy(+0x4f161)[0x5649db733161]
./mtproto-proxy(engine_init+0xe5)[0x5649db7294d5]
./mtproto-proxy(default_main+0x113)[0x5649db72a313]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fd035e251c1]
./mtproto-proxy(_start+0x2a)[0x5649db6f527a]
[pid 90855] [time 1531332115] -------------------------------
[pid 90855] [time 1531332115] mtproxy-0.01 compiled at Jul 11 2018 21:00:15 by gcc 7.2.0 64-bit after commit 20824f5fa8af3939e667fba5c1785f02059c1c43mtproto-proxy: common/pid.c:42: init_common_PID: Assertion `!(p & 0xffff0000)' failed.
[pid 90855] [time 1531332115]
root@proxy:/opt/MTProxy# [pid 90856] [time 1531332115]
------- Stack Backtrace -------
./mtproto-proxy(print_backtrace+0x2c)[0x5649db72f0fc]
./mtproto-proxy(extended_debug_handler+0x10)[0x5649db72f280]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13150)[0x7fd0361f7150]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fd035e3b0bb]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16d)[0x7fd035e3cf5d]
/lib/x86_64-linux-gnu/libc.so.6(+0x2ef17)[0x7fd035e32f17]
/lib/x86_64-linux-gnu/libc.so.6(+0x2efc2)[0x7fd035e32fc2]
./mtproto-proxy(+0x4f161)[0x5649db733161]
./mtproto-proxy(engine_init+0xe5)[0x5649db7294d5]
./mtproto-proxy(default_main+0x113)[0x5649db72a313]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fd035e251c1]
./mtproto-proxy(_start+0x2a)[0x5649db6f527a]
[pid 90856] [time 1531332115] -------------------------------
[pid 90856] [time 1531332115] mtproxy-0.01 compiled at Jul 11 2018 21:00:15 by gcc 7.2.0 64-bit after commit 20824f5fa8af3939e667fba5c1785f02059c1c43[pid 90856] [time 1531332115]

**Comment by t0xa2000** [comment]
in dmesg:
[2270250.698164] traps: mtproto-proxy[64569] trap invalid opcode ip:5594ebfa7ea1 sp:7fffcebc7020 error:0 in mtproto-proxy[5594ebf89000+6c000]

**Comment by stek29** [comment]
#41
