### ISSUE TITLE
question: Do I need to restart mtproto-proxy after update proxy-multi.conf?

### ISSUE THREAD

**Issue by kzhui125** [TelegramMessenger/MTProxy#170]
Obtain current telegram configuration. It can change (occasionally), so we encourage you to update it once per day.

curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf

**Comment by stek29** [comment]
yes, yo do

**Comment by kzhui125** [comment]
I see the log: configuration file proxy-multi.conf re-read successfully

**Comment by dvershinin** [comment]
@stek29 so do we have to restart or not? :) the log says the file is being re-read so why we have to restart then?
