### ISSUE TITLE
How To Cluster 2 Linux Ubuntu VPS For High Availability? 

### ISSUE THREAD

**Issue by alirezashahrokhi** [TelegramMessenger/MTProxy#171]
Hi All Dears
I Have 2 VPS In Iran
2 Iran VPS Forwarded The Traffic To France And Netherlands VPS 
I Need Cluster This 2 VPS 
Any Idea?

**Comment by jamesfirstv** [comment]
What means "make cluster"? You whant pass traffic or something else?

**Comment by alirezashahrokhi** [comment]
Dear @jamesfirstv 
I need Changed 2 nodes To 1 cluster Server For Best Uptime

**Comment by shadowlmd** [comment]
You can set up two A records for a domain name and provide it instead ow IP addresses. This way load will be balanced between two servers.
