### ISSUE TITLE
What's mean "dd" in MTProto Proxy secret

### ISSUE THREAD

**Issue by itsMoji** [TelegramMessenger/MTProxy#172]
Hi
What is different between normal hex secret and dd+secret in MTProto Proxy?

Telegram clients can connect to MTProxies in both normal secret and dd+secret format

**Comment by stek29** [comment]
dd+secret makes clients add random padding to some packets to make DPI detection of mtproxy harder.

**Comment by CraftedCat** [comment]
show how to generate this secret

**Comment by masoudelete** [comment]
i used 
`-S "dd" + <secret>`
but it didnt work

**Comment by d0tfile** [comment]
@masoudelete use "dd" prefix on client side

**Comment by masoudelete** [comment]
you mean in here? :
`tg://proxy?server=SERVER_NAME&port=PORT&secret=dd<secret>`

**Comment by Asamasach** [comment]
> you mean in here? : `tg://proxy?server=SERVER_NAME&port=PORT&secret=dd<secret>`

yes! that does work for me!

**Comment by amber46** [comment]
head -c 15 /dev/urandom | xxd -ps
