### ISSUE TITLE
dd prefix don't work

### ISSUE THREAD

**Issue by f242** [TelegramMessenger/MTProxy#175]
added **dd** to my secret 4aefc927021b522a491c2727380a5114 in client 
**dd**4aefc927021b522a491c2727380a5114 and cant't connect, after remove prefix all works fine

**Comment by AC130USpectre** [comment]
Probably it should works only on the latest version of proxy server. https://github.com/TelegramMessenger/MTProxy/commit/cf26efc6367ef3a30cde96ba76d6eaf11871a10a
Have you updated your proxy server?

**Comment by f242** [comment]
@AC130USpectre i think my sever is updated, from [this image](https://github.com/TelegramMessenger/MTProxy/issues/169#issuecomment-404650296)

**Comment by stek29** [comment]
What client are you using?

**Comment by f242** [comment]
@stek29 v1.3.10 alpha telegram desktop

**Comment by shadowlmd** [comment]
Please run this command inside your mtproxy docker container and post output here:
```
curl -s http://localhost:8888/stats | grep commit
```

**Comment by HamedFayez** [comment]
you most update your telegram client. then it's worked perfectly

**Comment by f242** [comment]
@shadowlmd  i find in logs `[1][2018-07-22 23:18:04.068713 local] Invoking engine mtproxy-0.01 compiled at Jun 10 2018 23:53:46 by gcc 6.3.0 64-bit after commit 20824f5fa8af3939e667fba5c1785f02059c1c43`
i suspect that my proxy is outdated, it's very strange because image was automaticaly built 2018-07-12, after 2 days from last commit with dd support

**question to telegram team**: why you don't support in actual state oficial mtproxy docker image?

**Comment by shadowlmd** [comment]
@f242, well, at least now you know the reason.
