### ISSUE TITLE
MTProxy is a failed project and it is all on Telegram managers.

### ISSUE THREAD

**Issue by FreedomPrevails** [TelegramMessenger/MTProxy#178]
Hello guys,
I am the author of JSMTProxy. I warned telegram admins on 31 May that this design is flawed and can be detected and filtered EASILY. here is the last issue which is closed by Telegram admins :
https://github.com/TelegramMessenger/MTProxy/issues/35
I even gave them the solution, switch the encryption to TLS. but the arrogance of Telegram admins is unprecedented. anyone who knows the internet censorship basics knows that you should NOT make a custom protocol if you want to blend in the white listed traffic.
MTProxy is almost dead here in Iran, I have created several personal MTProxy servers recently but they all get blocked in 2 or 3 days. I do not even recommend MTProxy to anyone anymore.
in other hand All SSL based VPNs work here like a champ.
It is so sad to see such a project fail because of such a disaster design and all suggestions fall on deaf ears.
I am sorry to say Telegram Fu... up so hard.
If I was Durov, I would fire anyone who designed this protocol immediately. the lack of knowledge here is astonishing.
Please upvote if you agree,

**Comment by xhdix** [comment]
JSMTProxy not updated version.
Use this repository (current) and set `dd` prefix to secret code.
