### ISSUE TITLE
Better Proxy Links: "Obscure Proxy Links"

### ISSUE THREAD

**Issue by minanoot55** [TelegramMessenger/MTProxy#180]
A proposal for an simple but very effective way of making proxy links much more effective and less prone to get blocked by governments: "Obscure Proxy Links".
Read more in here: https://github.com/minanoot55/telegram_secert_proxy_links

**Comment by minanoot55** [comment]
I know, this is not the best place to post this proposal, but didn't find any place better, what is your comment on this?

**Comment by stek29** [comment]
this would be rather easy to RE, and is imo outside of scope of telegram -- the idea is to have decentralized network of proxies, not to make one directory. have a look at other issues in this repo suggesting some official catalog of proxies.
