### ISSUE TITLE
MTProto and Calls

### ISSUE THREAD

**Issue by narimangharib** [TelegramMessenger/MTProxy#186]
May I ask if there is any reason to not supporting calls over MTProto? 

Thanks

**Comment by stek29** [comment]
because you can't use mtproto proxy for calls for technical reasons

**Comment by x90nik** [comment]
All about UDP protocol. Telegram calls over UDP, correct?

**Comment by x90nik** [comment]
https://core.telegram.org/api/end-to-end/voice-calls#mtproto-encryption
