### ISSUE TITLE
socks5 upstream

### ISSUE THREAD

**Issue by yknext** [TelegramMessenger/MTProxy#193]
How to set up an upstream Socks5 proxy

vps    <---encrypt proto--->   local server  (socks5://127.0.0.1:1080 <--> mtproxy )  <----mtproxy----> telegram client

This link, my phone only links to a local city IP, not a foreign IP, will not display foreign IP in the ISP traffic monitoring office

**Comment by stek29** [comment]
sorry, apps don't support that, and mtproxy can't be proxied currently (there's no such option in apps).
I didn't even understand what are you trying to accomplish.

**Comment by stek29** [comment]
I'm sorry, I didn't understand it's #143 duplicate
