### ISSUE TITLE
Error mtproto-proxy: command not found

### ISSUE THREAD

**Issue by Metal-Ghost** [TelegramMessenger/MTProxy#20]
Hi all
i try to run this proxy with command
mtproto-proxy -u VPN_And_Proxies -p 8888 -H 443 -S b587aa366b4a5b76bc2c5f42dc696900 --aes-pwd proxy-secret proxy-multi.conf -M 2
return 
mtproto-proxy: command not found
What do I do now?
(i tru run with other port
mtproto-proxy -u VPN_And_Proxies -p 5878 -H 4578 -S b587aa366b4a5b76bc2c5f42dc696900 --aes-pwd proxy-secret proxy-multi.conf -M 2
but see again this error
)
i ty use mtproto-proxy help 
but again return mtproto-proxy: command not found

**Comment by loskiq** [comment]
```cp objs/bin/mtproto-proxy /usr/local/bin```

**Comment by p1ratrulezzz** [comment]
```
ln -s path_to_mtproto/objs/bin/mtproto-proxy /usr/bin/mtproto-proxy
```

**Comment by Metal-Ghost** [comment]
Thanks 
if close terminal its run in background or not?

**Comment by p1ratrulezzz** [comment]
No it won't. Use systemd from second comment here https://github.com/TelegramMessenger/MTProxy/issues/19

Or use screen to run daemon in it.
