### ISSUE TITLE
The meaning of the file of basic service

### ISSUE THREAD

**Issue by Cost11** [TelegramMessenger/MTProxy#204]
{
[Unit]
Description=MTProxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 443 -S <secret> -P <proxy tag> <other params>
Restart=on-failure

[Install]
WantedBy=multi-user.target
}

This is author's example.
I saw the author's example, but some of the parameters in this configuration file I don't understand.
Does anyone know what the various parameters in this configuration file represent?
Especially “WorkingDirectory ”and “ExecStart”.
I will be very grateful，thanks！

**Comment by stek29** [comment]
Google systemd services docs
