### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Enlar** [TelegramMessenger/MTProxy#206]
`● MTProxy.service - MTProxy
   Loaded: loaded (/etc/systemd/system/MTProxy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-09-29 20:08:51 CEST; 15s ago
  Process: 17538 ExecStart=/usr/bin/mtproto-proxy -u nobody -p 8888 -H 4444 -S 4e72fa450a555129d2e3e
 Main PID: 17538 (code=exited, status=210/CHROOT)
      CPU: 848us

Sep 29 20:08:51 vmi200934.contaboserver.net systemd[1]: Started MTProxy.
Sep 29 20:08:51 vmi200934.contaboserver.net systemd[1]: MTProxy.service: Main process exited, code=e
Sep 29 20:08:51 vmi200934.contaboserver.net systemd[1]: MTProxy.service: Unit entered failed state.
Sep 29 20:08:51 vmi200934.contaboserver.net systemd[1]: MTProxy.service: Failed with result 'exit-co
lines 1-11/11 (END)`

**Comment by d0tfile** [comment]
Take ExecStart string (path to mtproto-proxy + args) from `/etc/systemd/system/MTProxy.service` and try to start mtproxy with that string. Show output.

**Comment by Enlar** [comment]
I am not an experienced user. Before the system reboot everything worked. Debian 9. Please, what exactly to write?

**Comment by d0tfile** [comment]
@Enlar `cat /etc/systemd/system/MTProxy.service`, copy line `ExecStart=...` and start manually.

**Comment by Enlar** [comment]
[4457][2018-10-02 16:07:10.494024 local] config_filename = 'proxy-multi.conf'
[4457][2018-10-02 16:07:10.495426 local] creating 1 workers
[4457][2018-10-02 16:07:10.495837 local] fatal: cannot load secret definition fi
le `proxy-secret'
[4458][2018-10-02 16:07:10.496009 local] fatal: cannot load secret definition fi
le `proxy-secret'

**Comment by d0tfile** [comment]
@Enlar seems like`proxy-multi.conf` is missing. Did you follow all steps from README?

**Comment by Enlar** [comment]
I don't know, just wrote a whole bunch of commands. It worked fine until the restart...
