### ISSUE TITLE
Limit MTProxy to One Telegram User id

### ISSUE THREAD

**Issue by m4h4n** [TelegramMessenger/MTProxy#218]
hi, it's a very useful option to add a Mtproxy Work limitation to one or more Telegram User id. 
it mean option to set a telegram user id on Mtproxy like `-valid-tg-id [userID1 userID2 userID3 ... ]` that this mtproxy online work and accept request from [userID1 userID2 userID3 ...] users.

i think it's not easily happen because of telegram security that not send user id to mtproxy servers, but i want a tool to make personal mtproxy only for low number of users like me and my friend and it's must not work for any other users that can get this mtproxy link.

**Comment by stek29** [comment]
> i think it's not easily happen because of telegram security that not send user id to mtproxy servers

exactly
