### ISSUE TITLE
Failed to start MTProxy

### ISSUE THREAD

**Issue by kooshkestani** [TelegramMessenger/MTProxy#219]
Hi I problem to connect to MTproxy
and check to issuse but not soulotion this problem

root@mosako:~/MTProxy/objs/bin# nano /etc/systemd/system/MTProxy.service
root@mosako:~/MTProxy/objs/bin# systemctl daemon-reload
root@mosako:~/MTProxy/objs/bin# systemctl restart MTProxy.service
Failed to restart MTProxy.service: Unit MTProxy.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status MTProxy.service' for details.
root@mosako:~/MTProxy/objs/bin# nano /etc/systemd/system/MTProxy.service
root@mosako:~/MTProxy/objs/bin# systemctl daemon-reload
root@mosako:~/MTProxy/objs/bin# systemctl restart MTProxy.service
root@mosako:~/MTProxy/objs/bin# systemctl status MTProxy.service
● MTProxy.service - MTProxy
   Loaded: loaded (/etc/systemd/system/MTProxy.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2018-11-22 04:49:39 EST; 3s ago
  Process: 19557 ExecStart=/opt/MTProxy/objs/bin/mtproto-proxy -u mosako -p 8888 -H 443 -S ad48a1b197c160f3aec7997fb55152e7 --aes-pwd proxy-secret proxy-multi.
 Main PID: 19557 (code=exited, status=200/CHDIR)

Nov 22 04:49:39 mosako systemd[1]: MTProxy.service: Unit entered failed state.
Nov 22 04:49:39 mosako systemd[1]: MTProxy.service: Failed with result 'exit-code'.
Nov 22 04:49:39 mosako systemd[1]: MTProxy.service: Service hold-off time over, scheduling restart.
Nov 22 04:49:39 mosako systemd[1]: Stopped MTProxy.
Nov 22 04:49:39 mosako systemd[1]: MTProxy.service: Start request repeated too quickly.
Nov 22 04:49:39 mosako systemd[1]: Failed to start MTProxy.

**Comment by kooshkestani** [comment]
[Unit]
Description=MTProxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy/objs/bin
ExecStart=/opt/MTProxy/objs/bin/mtproto-proxy -u mosako -p 8888 -H 443 -S ad48a1b197c160f3aec7997fb55152e7 --aes-pwd proxy-secret proxy-multi.conf -M 5
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by epm157** [comment]
Try to run it without creating service, i.e., run the following command in ssh terminal:
`/opt/MTProxy/objs/bin/mtproto-proxy -u mosako -p 8888 -H 443 -S ad48a1b197c160f3aec7997fb55152e7 --aes-pwd proxy-secret proxy-multi.conf -M 5`

**Comment by stek29** [comment]
post full log (`journalctl -u mtproxy`)

**Comment by leemessi** [comment]
try this,it works for me
```[Unit]
Description=MTProxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/root/MTProxy/objs/bin
ExecStart=/root/MTProxy/objs/bin/mtproto-proxy -u mosako -p 8888 -H 443 -S ad48a1b197c160f3aec7997fb55152e7 --aes-pwd proxy-secret proxy-multi.conf -M 5
Restart=on-failure

[Install]
WantedBy=multi-user.target```

**Comment by alexeevit** [comment]
I've resolved the trouble.
You should use an absolute path to config files:

```
[Unit]
Description=MTProxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy/objs/bin
ExecStart=/opt/MTProxy/objs/bin/mtproto-proxy -u mosako -p 8888 -H 443 -S ad48a1b197c160f3aec7997fb55152e7 --aes-pwd /opt/MTProxy/objs/bin/proxy-secret /opt/MTProxy/objs/bin/proxy-multi.conf -M 5
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by fish-404** [comment]
You can use the command `journalctl -u MTProxy -e` to see the log details.
Maybe you will meet the mistake below:
* 443 port has been used
* can't find the user "mosako"
* the path mistake
