### ISSUE TITLE
MTProto Proxies are getting blocked in Iran very fast!!! 

### ISSUE THREAD

**Issue by MR-Pooya** [TelegramMessenger/MTProxy#222]
Please do something about it
... ip server block on 1hour 😑
i edited the python source and use ip verification on it😑
i dont know how it blocked😑😑
PLEASE DO SOMETHING!

**Comment by Dragon-Knight** [comment]
1) Do not use the standard port.
2) Do not run other types of proxies on the server.
3) Close all ports (TCP, UDP, ICMP) except the MTP port.
4) Do not publish information about your proxy in public sources.
5) Use the dynamic packet length (add 'dd' to the key).

**Comment by Dragon-Knight** [comment]
The public proxy will be blocked a priori, something you would not do.

As an example, what prevents me from working on the blocking service and searching the network for a proxy server? And that is exactly how they block...

**Comment by hookzof** [comment]
> Thank you for reply but i do all of them
> Just i dont close udp and tcp port🤔
> I just close icmp data
> And we need to publish proxy in public channel
> But if you think they have cli bot in our channel we can use captcha bot
> But i think ... source have a little bug and they find this bug :(
> And about dynamic packet
> we edited orginal source and client only can connect with dynamic packet
> And again blocked :(

Do you use random padding to packs?
https://github.com/TelegramMessenger/MTProxy#random-padding

**Comment by CraftedCat** [comment]
You can convert ip to dec, https://www.browserling.com/tools/ip-to-dec , telegram client can convert themselve, but sponsored channel not be showed

**Comment by nekooee** [comment]
> 1. Do not use the standard port.
> 2. Do not run other types of proxies on the server.
> 3. Close all ports (TCP, UDP, ICMP) except the MTP port.
> 4. Do not publish information about your proxy in public sources.
> 5. Use the dynamic packet length (add 'dd' to the key).

Hi
I use Directadmin panel on centos and it's firewall only has TCP,UDP and ICMP port and not option for MTP port. when I open TCP port, proxy connect fine but very very slowly and telegram can`t download any files.
how I can Open only port MTP in directadmin or centos ?

**Comment by pooya-irpat** [comment]
> The public proxy will be blocked a priori, something you would not do.
> 
> As an example, what prevents me from working on the blocking service and searching the network for a proxy server? And that is exactly how they block...

i know what you say
but they detect our proxy very easily :(
we have 3 channel with 400k member , our proxy lifetime in 2 week ago about 2-3 days
but now... 1 hour -_-
and if you cant do anything
please add sponsor channel to Https proxy just for **Iranian users** we need it!
telegram popularity in danger :( 
please add Https proxy on client app and add sponsor channel  ♥
