### ISSUE TITLE
Can i run multiple instances?

### ISSUE THREAD

**Issue by pkka** [TelegramMessenger/MTProxy#234]
Can i do this and add multiple lines?

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 443 -S <secret> -P <proxy tag> <other 
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 444 -S <secret> -P <proxy tag> <other 
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 445 -S <secret> -P <proxy tag> <other 
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 443 -S <secret2> -P <proxy tag> <other 
Restart=on-failure

**Comment by stek29** [comment]
nope, you need to create multiple services (or use systemd's `@` feature, idk how is it named)

**Comment by pkka** [comment]
Do you mean this?:

[Unit]
Description=MTProxy
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 443 -S <secret> -P <proxy tag> <other params>
Restart=on-failure

[Install]
WantedBy=multi-user.target


[Unit]
Description=MTProxy2
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 443 -S <secret2> -P <proxy tag> <other params>
Restart=on-failure

[Install]
WantedBy=multi-user.target




[Unit]
Description=MTProxy2
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/MTProxy
ExecStart=/opt/MTProxy/mtproto-proxy -u nobody -p 8888 -H 444 -S <secret> -P <proxy tag> <other params>
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by pkka** [comment]
or create another MTProxy2.service file?
