### ISSUE TITLE
error mtproto-proxy: command not found

### ISSUE THREAD

**Issue by mahdihk** [TelegramMessenger/MTProxy#24]
Hi all
i try to run this with command
mtproto-proxy -u mahdihk -p 1080 -H 6969 -S 55cf808f42b97f44c2ca09a847d7764c --aes-pwd proxy-secret proxy-multi.conf -M 1
and return
mtproto-proxy: command not found
what can i do?

**Comment by feedb** [comment]
read readme please

**Comment by feedb** [comment]
objs/bin/mtproto-proxy for you

**Comment by Gargae** [comment]
It may be necessary to add "./" at the beginning of the text
./mtproto-proxy -u mahdihk -p 1080 -H 6969 -S 55cf808f42b97f44c2ca09a847d7764c --aes-pwd proxy-secret proxy-multi.conf -M 1

**Comment by mahdihk** [comment]
try
 ./mtproto-proxy -u mahdihk -p 1080 -H 6969 -S 55cf808f42b97f44c2ca09a847d7764c --aes-pwd proxy-secret proxy-multi.conf -M 1

-bash: ./mtproto-proxy: No such file or directory

**Comment by feedb** [comment]
you make source?

**Comment by mahdihk** [comment]
cc -m64 -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"2fd27cb0753c62e5766c86db28f2acc1d755547f\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
make: cc: Command not found
Makefile:78: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 127

**Comment by mahdihk** [comment]
cc -m64 -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"2fd27cb0753c62e5766c86db28f2acc1d755547f\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
make: cc: Command not found
Makefile:78: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 127

**Comment by loskiq** [comment]
@mahdihk You need install ```gcc```

Debian/Ubuntu: ```apt-get install gcc make```
CentOS: ```yum install gcc```
