### ISSUE TITLE
random padding on docker

### ISSUE THREAD

**Issue by aminvakil** [TelegramMessenger/MTProxy#242]
I understand docker image is outdated and as it seems random padding doesn't work on docker image of mtproto, but I wonder is there a way to implement it on docker too.

I'm willing to implement it myself if there is some advice or custom configuration which can be done on docker image.

**Comment by hookzof** [comment]
https://hub.docker.com/r/homdx/mtproxy

**Comment by stek29** [comment]
You'd have to use some unofficial docker image, like one above.
