### ISSUE TITLE
make && cd objs/bin errors

### ISSUE THREAD

**Issue by kooran** [TelegramMessenger/MTProxy#247]
Hello , I'm using CentOS 6.4, i did all steps fine till make && cd objs/bin, i get this error: 
```
cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"b9950a18f8f289837545a5152c2fd423717c0b48\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
cc1: error: unrecognized command line option "-std=gnu11"
make: *** [objs/mtproto/mtproto-proxy.o] Error 1
```
i searched and tried to install openssl, do make clean, ...
but none of them worked, i don't know what else to do

**Comment by CraftedCat** [comment]
@kooran


wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
    yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++ -y
    export CC=/opt/rh/devtoolset-2/root/usr/bin/gcc  
    export CPP=/opt/rh/devtoolset-2/root/usr/bin/cpp
    export CXX=/opt/rh/devtoolset-2/root/root/usr/bin/c++

And try again

**Comment by kooran** [comment]
@CraftedCat 
it worked!!! thanks a lot!! i wish i could learn how to fix these kind of issues myself ♥

**Comment by Alone700** [comment]
Hello from the server centos7 I use it to use a proxy
But I enter the following code and I encounter the following error
make && cd objs/bin
make && cd objs/bin                       cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"dc0c7f3de40530053189c572936ae4fd1567269b\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
mtproto/mtproto-proxy.c:42:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>

help me ):
