### ISSUE TITLE
error in kali 

### ISSUE THREAD

**Issue by laknes** [TelegramMessenger/MTProxy#25]
cc -m64 -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"2fd27cb0753c62e5766c86db28f2acc1d755547f\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
mtproto/mtproto-proxy.c:42:10: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:78: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 1

what is that problem please help

**Comment by BlackSuited** [comment]
OpenSSL is missing :|

**Comment by laknes** [comment]
How can I install it

**Comment by p1ratrulezzz** [comment]
install package libssl-dev

But you could do this by googling
