### ISSUE TITLE
can't get stats

### ISSUE THREAD

**Issue by apepenkov** [TelegramMessenger/MTProxy#253]
root@vps7987:~# wget localhost:8888/stats
--2019-01-28 16:52:33--  http://localhost:8888/status
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8888... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8888... failed: Connection refused.

**Comment by AlexMTX** [comment]
According to https://github.com/TelegramMessenger/MTProxy/commit/28f5b17eef2f50d768c4f010f8a4fc149254550a#diff-ac131e76077c0e274e1b894e161a1047R2225
you need to add --http-stats argument to the command line

**Comment by apepenkov** [comment]
Damn, I cant check it now, proxy is using by people. Ill reopen if it wouldn't work as soon as possible.

**Comment by onikethem** [comment]
Oh my god 🤕🤕🤕

در دوشنبه ۲۸ ژانویهٔ ۲۰۱۹،‏ ۲۲:۳۴ apepenkov <notifications@github.com نوشت:
