### ISSUE TITLE
How to update to latest version?

### ISSUE THREAD

**Issue by AndyFresh** [TelegramMessenger/MTProxy#256]
Hello. I have version mtproxy-0.01 compiled at Jun  1 2018 12:06:27 by gcc 5.4.0 20160609 64-bit after commit e231d049362476be7f3c1cbe8fa0d22b76d698dd
And I want to update MTProxy up to latest version to use 'dd' prefix. How can I do it? Sorry, I'm newbie to this.
I think that some instruction may be helpful.

**Comment by onikethem** [comment]
🤔

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۲:۰۲ AndyFresh <notifications@github.com نوشت:

**Comment by HirbodBehnam** [comment]
Hello 
There is no specific way to upgrade. You need to rebuild the proxy yourself. You have to clone the project and build it again. And dont use docker as it's outdated. 

Also if you server's OS is Centos 7, you can have a look at my automatic installer. [Link](https://github.com/HirbodBehnam/MTProtoProxyCentOSInstall)

**Comment by onikethem** [comment]
I am investing. Anyone have a telegram channel to share my proxy links. I
can pay a paycheck 1 bitcoin

در جمعه ۱ فوریهٔ ۲۰۱۹،‏ ۱۴:۴۱ Hirbod Behnam <notifications@github.com نوشت:

**Comment by AlexMTX** [comment]
If you have installed it according to a readme, you must have a MTProto git repository. Update it, rebuild and update the service:
git pull
make
systemctl daemon-reload
systemctl restart MTProxy.service
# Check status, it should be active
systemctl status MTProxy.service

**Comment by AndyFresh** [comment]
@AlexMTX thx, it was helpful! I've update it :)
