### ISSUE TITLE
How to promote a channel?

### ISSUE THREAD

**Issue by Plz69** [TelegramMessenger/MTProxy#26]
Hi,

I run a mtproto server and add my proxy and channel to MTProxybot.
https://t.me/MTProxybot

But, I cant see my channel in top with tag "Proxy Sponsored".

**Comment by MasterGroosha** [comment]
After you register your proxy with [@MTProxyBot](https://t.me/mtproxybot), you'll be given a special `tag` ("You can now pass this proxy tag to the software you are using: abc123xyz....").

You should pass it to mtproxy binary as `-P` argument, for example,
`mtproto-proxy -u nobody -p 8888 -H 443 -S <secret>-P abc123xyz --aes-pwd proxy-secret proxy-multi.conf -M 1`

Don't forget to setup a sponsored channel via bot.

**Comment by Keikhosro11** [comment]
I did not get it,
Instead of  abc123xyz I will replace my tag?

**Comment by MasterGroosha** [comment]
@Keikhosro11, yes instead of `abc123xyz` use what MTProxyBot sent to you.

**Comment by savimisha** [comment]
As I think, you will never get a promotion because you created this proxy. Try use it with another Telegram account.

**Comment by MasterGroosha** [comment]
@savimisha What do you mean?

**Comment by stek29** [comment]
You won’t see channel as promoted if you’ve joined it.
