### ISSUE TITLE
How generete this secret code?

### ISSUE THREAD

**Issue by ghazdir34** [TelegramMessenger/MTProxy#260]
https://t.me/proxy?server=Victoria.dynu.com&port=8080&secret=00000000000000000000000000000000

I think this secret is encrypt

**Comment by onikethem** [comment]
داداش کجایی تو ایرانی هستی این ایدی منه بهم پیام بده
https://t.me/Bet_cup24

در سه‌شنبه ۱۲ فوریهٔ ۲۰۱۹،‏ ۱۱:۳۷ ghazdir34 <notifications@github.com نوشت:

**Comment by d0tfile** [comment]
https://github.com/TelegramMessenger/MTProxy#running
`head -c 16 /dev/urandom | xxd -ps`
