### ISSUE TITLE
How to make Mtproto listen to many ports?

### ISSUE THREAD

**Issue by DenisGribanov** [TelegramMessenger/MTProxy#267]
Hello, how to make Mtproto listen to many ports? for example: 443,8081,843,8888

**Comment by d0tfile** [comment]
Run multiple instances or redirect traffic from needed ports to MTProxy single port (not sure if it will work, but seems legit)

**Comment by uprt** [comment]
You can try something like that:
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8888
iptables -t nat -A PREROUTING -p tcp --dport 843 -j REDIRECT --to-port 8888
iptables -t nat -A PREROUTING -p tcp --dport 8081 -j REDIRECT --to-port 8888
