### ISSUE TITLE
enable proxy for calls button disappears in telegram android when enabling proxy

### ISSUE THREAD

**Issue by danyhm** [TelegramMessenger/MTProxy#268]
When there are no proxies in proxy list in telegram android there's a button that says "Use proxy for calls".

after adding a proxy server that option disappears and I can't make a call with proxy.

Does anyone know what the problem is ? or how can I use proxies to make a call ?

**Comment by HirbodBehnam** [comment]
MTproto cannot route calls; Use socks instead.

**Comment by danyhm** [comment]
john-preston mentioned it doesn't work for call. the problem is that socks is filtered in Iran. so no call options ....
Thanks for replying anyway.

**Comment by HirbodBehnam** [comment]
Yw
You can use VPN to use telegram call; You can give a try to shadowsocks and wireguard.
