### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Enlar** [TelegramMessenger/MTProxy#273]
MTProxy.service - MTProxy
   Loaded: loaded (/etc/systemd/system/MTProxy.service; disabled; vendor preset:
   Active: failed (Result: exit-code) since Tue 2019-03-05 14:42:13 MSK; 10s ago
  Process: 32759 ExecStart=/usr/bin/mtproto-proxy -u root -p 8888 -H 1194 -S c84
 Main PID: 32759 (code=exited, status=210/CHROOT)

Mar 05 14:42:13 v110654.hosted-by-vdsina.ru systemd[1]: Started MTProxy.
Mar 05 14:42:13 v110654.hosted-by-vdsina.ru systemd[1]: MTProxy.service: Main pr
Mar 05 14:42:13 v110654.hosted-by-vdsina.ru systemd[1]: MTProxy.service: Unit en
Mar 05 14:42:13 v110654.hosted-by-vdsina.ru systemd[1]: MTProxy.service: Failed

**Comment by stek29** [comment]
error messages are cropped, please post full logs

**Comment by Enlar** [comment]
resolved
