### ISSUE TITLE
Random padding is still weak to DPI

### ISSUE THREAD

**Issue by wfjsw** [TelegramMessenger/MTProxy#281]
### Situation

As current random padding implemention current only add 1-3 bytes after original packet(which is fixed size), it is still not a big deal for DPI filters to block MTProxy traffic by packet size. Although this prevents fixed-size packet filter, one can setup filters with a relatively small size window (0-4 bytes), without enough risk for blocking other connections.

According to my survey, currently this blocking strategy (or something similar) is possibly implemented in some countries' firewall. 

I haven't spotted any other issue in proxy protocol.

### Proposal

1. Easy approach - add more random bytes instead of just 1-3.
2. Split packet into smaller part.
3. Make it possible to chain multiple proxies together. (For example, strip `local_ip` and `local_port` out of PROXY <=> Telegram connection key so it is possible to run MTProxy behind firewall, pack the data stream into another reliable protocol and use this to bypass firewall, as I described [here](https://github.com/TelegramMessenger/MTProxy/issues/143#issuecomment-398262070))

**Comment by hookzof** [comment]
Modification of this solution is absolutely necessary.

**Comment by wfjsw** [comment]
After conversation with TDLib developer, I realize the padding actually lies in application protocol between Client and Server (This is not responsibility of MTProxy). My simulation is getting negative blocking result with these extra padding present.

My simulation script is available here: https://github.com/wfjsw/FakeMTProxy

To simulate ordinary connection without `dd` use `-p` with `abridged`
To simulate what this issue illustrates use `-p` with `secure`
To simulate current implemention, use `-p -ps` and `-psl` (optional) with `secure`

Closing this issue now.

**Comment by masoudelete** [comment]
I can't upload images with certain ISP's and I can't figure out how to use code, can you write a newbie how to run?
