### ISSUE TITLE
my ips block every 3 hours can help me?

### ISSUE THREAD

**Issue by bornajouya** [TelegramMessenger/MTProxy#289]
my ips block every 3 hours and i just change it it seems the cnd and other ways dont work cant anyone help me to finish or reduse blocking ip?

**Comment by kevinjobs** [comment]
Are you sure that ip was blocked? Maybe the port is blocked.
You can try a new port.

**Comment by Ham3dn** [comment]
@kevinjobs tell me how can I change it?
