### ISSUE TITLE
MTProto Proxy is not perfect

### ISSUE THREAD

**Issue by hookzof** [TelegramMessenger/MTProxy#290]
The average time to detect a public proxy in Russia is from 20 to 40 minutes. 40-50 IP-addresses are burning down per day, auto-change of the address is working.

**2 disadvantages that interfere with the work of the proxy:**

1. Open transfer of IP-address through domain/subdomain.

> One possible solution:
> 1.1 Encrypt a domain/subdomain by signing it with a secret key (proxy) and port.
> 1.2 On the client side, decrypt only a portion of the metadata to establish a connection between proxy server and telegram.

2. Wrap all traffic in HTTPS/TLS.

UPD 20.04.19: 3. Active fingerprinting detection and blocking. New proxy detection method (active in Iran and China, expected in Russia :)) Problems: [here](https://github.com/TelegramMessenger/MTProxy/issues/293) and [here](https://github.com/alexbers/mtprotoproxy/issues/83).

Eliminating these shortcomings will complicate proxy detection.

### Please support this topic.

**Comment by stek29** [comment]
@hookzof how does "encrypting domain" help? Not even talking about technical difficulties.

**Comment by hookzof** [comment]
> @hookzof how does "encrypting domain" help? Not even talking about technical difficulties.

Русскоговорящему, я лучше объясню по-русски. В Telegram знали, что основная часть прокси-серверов будет публичной, и практически ничего не сделали, чтобы хоть как-то скрыть адрес по которому пользователь подключается. Сделали случайное заполнение к пакетам, да это хорошо конечно, но этого не достаточно.

Как будут скрывать и будут ли вообще это делать, мне без разницы. Сколько IP-адресов угробилось уже, сделав чуть раньше то, что я расписал выше, могли бы сократить расходы на нет

**Comment by stek29** [comment]
@hookzof Как вы вообще представляете себе скрытие адресов с технической точки зрения?

**Comment by hookzof** [comment]
> @hookzof Как вы вообще представляете себе скрытие адресов с технической точки зрения?

Под сокрытием адреса я предполагаю подключение к прокси не через домен, а через ключ например, который нельзя зарезолвить. IP-адрес понятное дело, что не скроешь, но можно весь трафик завернуть в https/tls.

**Comment by alxdrlitreev** [comment]
Totally meaningless. 

First of all, there's no need at the moment to use HTTPS/TLS as a tunnel protocol, since there's already `dd+secret` mode implemented by Telegram team. It automatically adds random padding to some packets to make DPI-based detection of MTProto nearly impossible.

> Open transfer of IP-address through domain/subdomain.

Just as @stek29 mentioned, it is not even about technical details. There's no way to hide an IP address of a proxy server, since there's *always* will be some users, who are willing to share their settings with the others. You can't just make such things visible for good guys only. Moreover, there's DNS-over-TLS coming soon (see — https://tools.ietf.org/html/rfc7858). But once again — if there's proxy server for more than just one person, it will be somehow leaked to government authorities anyway.

**Comment by artemtam** [comment]
1. Простите, но это какая-то ерунда. Как можно _скрыть адрес_, если IP-адрес сервера виден на сетевом уровне? Предлагаете переписать протокол IP?

2. В HTTPS тоже нет совершенно никакого смысла. Обфусцированные бинарные данные MTProto справляются со своей задачей прекрасно. Оборачивание их в TLS создаст много проблем: например, доменное имя сервера будет открыто передаваться при каждом запросе (SNI), от чего вы как раз хотите избавиться. Ну и про дополнительный существенный оверхэд вы тоже не забывайте.

**Comment by hookzof** [comment]
> * Простите, но это какая-то ерунда. Как можно _скрыть адрес_, если IP-адрес сервера виден на сетевом уровне? Предлагаете переписать протокол IP?
> * В HTTPS тоже нет совершенно никакого смысла. Обфусцированные бинарные данные MTProto справляются со своей задачей прекрасно. Оборачивание их в TLS создаст много проблем: например, доменное имя сервера будет открыто передаваться при каждом запросе (SNI), от чего вы как раз хотите избавиться. Ну и про дополнительный существенный оверхэд вы тоже не забывайте.

1. Под адресом подразумеваться домен, не перевирайте слова.

2. За оверхэд я не беспокоюсь, достаточные мощности для этого есть.

**Comment by artemtam** [comment]
Хорошо, правильно я понимаю, что речь о том, чтобы каким-то образом скрыть
домен публичного прокси именно при его распространении?

**Comment by hookzof** [comment]
> Хорошо, правильно я понимаю, что речь о том, чтобы каким-то образом скрыть домен публичного прокси именно при его распространении?
> […](#)

Именно так, первый пункт можно реализовать по другому, прокси-сервер подключается напрямую к телеграму, тем самым находясь в локальной сети и не светит IP-адрес (условно как TOR).

**Comment by artemtam** [comment]
Но в локальной сети с устройствами пользователей он находиться не будет. В
любом случае нужен публичный IP, по которому будут подключаться
пользователи и, соответственно, видимый для РКН.

Не вижу другого решения, кроме как часто-часто менять IP. Нужен какой-то
абсолютно другой подход к решению этой проблемы.

**Comment by hookzof** [comment]
> Но в локальной сети с устройствами пользователей он находиться не будет. В любом случае нужен публичный IP, по которому будут подключаться пользователи и, соответственно, видимый для РКН. Не вижу другого решения, кроме как часто-часто менять IP. Нужен какой-то абсолютно другой подход к решению этой проблемы.
> […](#)

Этот подход уже наверно реализован в TON, и остается только ждать релиза.

**Comment by jamesfirstv** [comment]
Мне кажется в словах @hookzof есть смысл. Пусть в приложении ТГ пользователю (и РКН) даётся ссылка вида https://t.me/proxy/[hash], пусть пользователи меняются именно ею, хорошо, что она не резолвится в ip штатными средствами ОС (gethostbyname();). Но она может ресолвится самим клиентом ТГ, и тогда у противника останется только путь лабораторных испытаний, чтобы добавлять адреса в базу блокировки

**Comment by clsv** [comment]
> Мне кажется в словах @hookzof есть смысл. Пусть в приложении ТГ пользователю (и РКН) даётся ссылка вида [https://t.me/proxy/[hash]](https://t.me/proxy/%5Bhash%5D), пусть пользователи меняются именно ею, хорошо, что она не резолвится в ip штатными средствами ОС (gethostbyname();). Но она может ресолвится самим клиентом ТГ, и тогда у противника останется только путь лабораторных испытаний, чтобы добавлять адреса в базу блокировки

Не такая плохая идея, отсевает парсинг каналов/сайтов, остается только ручной режим, добавлять прокси в клиент и смотреть статистику соединений.

**Comment by jamesfirstv** [comment]
@artemtam тоже хорошо предлагает: создать кооператив админов прокси, но выступить всем разом под, например, одним хэш-доменом, и резолвить его в разных регионах на разные хосты. Тогда даже в результате лабораторных испытаний невозможно будет быстро отсканировать всех членов кооператива, что сделает хэш-домен неблокируемым

**Comment by velsa** [comment]
В любом случае, блокировать будут не только телеграм и большинству людей потребуется какой-то вариант VPN. 

Я какое-то время назад придумал и описал свою идею "кооператива админов", которые помогают организовать персональные VPN сервера для обычных людей. Можете посмотреть статью на хабре: https://habr.com/ru/post/354956/. Само техническое решение нужно додумывать, но концепт должен быть понятен: дать возможность технически подкованным людям (админам) создавать удобный VPN для своих друзей и знакомых.

К сожалению, под этот проект не удалось найти команду энтузиастов...

**Comment by darkk** [comment]
&lt;offtopic&gt;
@velsa Google Jigsaw сделали интересный ход в направлении _"сам себе VPN"_ под названием [Outline](https://getoutline.org/). Это как [Algo](https://github.com/trailofbits/algo) или [Streisand](https://github.com/StreisandEffect/streisand), но "с человеческим лицом".
&lt;/offtopic&gt;

**Comment by rlka** [comment]
> Мне кажется в словах @hookzof есть смысл. Пусть в приложении ТГ пользователю (и РКН) даётся ссылка вида https://t.me/proxy/[hash], пусть пользователи меняются именно ею, хорошо, что она не резолвится в ip штатными средствами ОС (gethostbyname();). Но она может ресолвится самим клиентом ТГ, и тогда у противника останется только путь лабораторных испытаний, чтобы добавлять адреса в базу блокировки

как ресолвить телеграмом, если телеграм забанен?

**Comment by jamesfirstv** [comment]
> как ресолвить телеграмом, если телеграм забанен?

1) Телеграм работает, даже если забанен, через TON P2P. Мультимедиа не грузиться, но все функции TON от сообщений до оплаты должны работать

2) TON DHT уже реализует идею хэш-ссылок на объекты сети, и мог бы заменить ссылки вида t.me/proxy/[hash]

3) TON DNS поможет выдать нормальные имена и скрыть страшные хэши с глаз пользователей

4) Но я не нашёл достаточно информации о туманных (shadow) сервисах, т.к. кооператив проксей по смыслу им и является

Итого: нужно больше информации и полный запуск TON

**Comment by hanayashiki** [comment]
Can't you guys talk some English? Chinese are also interested.

**Comment by stek29** [comment]
@hanayashiki there's just a bunch of Ton speculation bs, not worth it.

**Comment by pav5000** [comment]
> Totally meaningless.
> 
> It automatically adds random padding to some packets to make DPI-based detection of MTProto nearly impossible.

My ISP (YOTA) just slows down to 64kbps all protocols that it cannot detect. So while detection is "nearly impossible", in real life it sometimes acts against the proxy. Being able to tunnel traffic via valid https on valid domain, just on "secret URL" would be a killer-feature against evil ISPs.
