### ISSUE TITLE
Telegram x => Not connecting

### ISSUE THREAD

**Issue by ranjbarhadi** [TelegramMessenger/MTProxy#293]
since today ( Wednesday - 2019 17 April ) this script is not connecting on Telegram x. both on Android and IOS. official Telegram app on Android and IOS and PC is working just fine. what should we do?

**Comment by stek29** [comment]
Telegram X on iOS is just an outdated version of normal app.

are you able to connect to other proxies?

**Comment by ea1234567** [comment]
i had same problem:

https://github.com/alexbers/mtprotoproxy/issues/83

i think this is new censorship method
im changed my server ip and problem solved

**Comment by ea1234567** [comment]
and when i turned on vpn my problem solved

**Comment by jahmadiiiii** [comment]
> 
> 
> Telegram X on iOS is just an outdated version of normal app.
> 
> are you able to connect to other proxies?

i have same problem in Telegram X 0.21.3.1036 android version and in Telegram Desktop 1.6.7.

in android version of Telegram there is no problems.

just in Telegram X MTPROTO not working or some time some of proxeis working with Cloud flare DNS.
Http and Socks 5 Proxies wont work any more in Telegram X of android i mention.

In Desktop version Http proxies work well but some MTPROTO Proxeis Work.

**Comment by ea1234567** [comment]
@jahmadiiiii
Im sure this is new censorship method
turn your vpn on and test again problem will be solved and now you can connect to your proxy

**Comment by jahmadiiiii** [comment]
@ea1234567 i know about that but vpn consume battery and internet!

with VPNs i have nor problem to connect!

**Comment by ea1234567** [comment]
jahmadiiiii
I just want to say this is censorship
this isnt telegram problem

**Comment by jahmadiiiii** [comment]
@ea1234567 thank you for help

**Comment by ranjbarhadi** [comment]
update on this issue. telegram x on both IOS and android is working again. I didn't update my telegram x. so something must be happening with the censorship methods that are using by the government in Iran.

**Comment by ranjbarhadi** [comment]
Exactly 2 minutes after posting this my MTproxy stop working. it's like the IP has been banned in Iran :| 

> update on this issue. telegram x on both IOS and android is working again. I didn't update my telegram x. so something must be happening with the censorship methods that are using by the government in Iran.

**Comment by maincui** [comment]
> update on this issue. telegram x on both IOS and android is working again. I didn't update my telegram x. so something must be happening with the censorship methods that are using by the government in Iran.

hi, @ranjbarhadi , where do you find Telegram X for **Android**? I couldn't find the open source any where? Besides, Both Iran and China are suffering network blocking, how do you get it done by MTProxy? Can users of your own app message without setting proxy for themselves?

**Comment by ranjbarhadi** [comment]
> where do you find Telegram X for Android?

@maincui telegram x is currently in play store. you can download it.

> how do you get it done by MTProxy?

well, I simply buy a small server for my personal use. I clone this repository and run it as a service.  and I always use random padding.

**Comment by maincui** [comment]
@ranjbarhadi , I thought you got Telegram X in source code. now I know you got the Telegram X app from play, and built MTProxy and configured it as a proxy to the app so that they both worked together without being blocked. That's great, but a bit different from my requirements.

Besides, Telegram X for android cant add contacts when viewing someone's profile, but Telegram for android can. That's weird, they behave inconsistently.
