### ISSUE TITLE
To do the work of the port stats not only through localhost

### ISSUE THREAD

**Issue by k0st1an** [TelegramMessenger/MTProxy#310]
Please make it possible to get statistics not only through localhost. Maybe adjust it a separate key? This would be very handy when using Docker.

**Comment by thelebster** [comment]
@k0st1an, try [this repo](https://github.com/thelebster/mtproxy-docker) with some minor overrides and Nginx configuration example for /stats endpoint.

**Comment by k0st1an** [comment]
@thelebster thanks. But for my needs does not fit.
