### ISSUE TITLE
MTProxy is stupid

### ISSUE THREAD

**Issue by pkka** [TelegramMessenger/MTProxy#313]
How the hell are they detecting my MTProxy and blocking its IP? I never publish my MTProxy info anywhere. I haven't looked at source code but i guess MTProxy is stupid and if somebody scan my server ports then MTProxy responds hey its me, im a proxy, please block me. please change this. nobody should be able to detect im running mtproxy without knowing my secret.

**Comment by ed96win** [comment]
[D]eep [P]acket [I]nspection my friend.

**Comment by stek29** [comment]
no u
