### ISSUE TITLE
cannot connect from Iran

### ISSUE THREAD

**Issue by sahareh** [TelegramMessenger/MTProxy#319]
I recently used this proxy on Hetzner data center (Germany) but cannot connect from Iran.
I know this is not your business but just for knowledge sharing I explain the situation:
when I listen on a port by `nc`  command and then communicate with it from iran by `telnet` command just first message is sent and other messages never sent while connection is still open without closing from server or client.
can anyone help me or make this proxy works on such situations?

**Comment by Momenimahdi2** [comment]
Manam az hamin data center gereftam vali vasl shod vali bad az 20 min filter shod chikar konam ke filter nashe?

**Comment by mostafaznv** [comment]
I have this problem too.
mtproto configuration is ok but I can't connect to server from iran

**Comment by sleeplife** [comment]
Check if IP is not banned

**Comment by oky2abbas** [comment]
I also have this problem

**Comment by ParsDev** [comment]
Random padding

Due to some ISPs detecting MTProxy by packet sizes, random padding is added to packets if such mode is enabled.

It's only enabled for clients which request it.

Add dd prefix to secret (cafe...babe => ddcafe...babe) to enable this mode on client side.

update it please
the ip server is filtered after 10 minutes in iran

**Comment by sleeplife** [comment]
as I said, sometimes, IP has been banned. and Random Padding does NOT work at all

most of time you can find out by ping the IP
if it works (wait till ping finish) then look for your configure problem

**Comment by HirbodBehnam** [comment]
Sometimes to check if your server is blocked, you can establish an SSH connection. If it gets stuck on ` expecting ssh key` or something your server is blocked

**Comment by ParsDev** [comment]
We need a new way to pass filtering in iran
example : change secret format

**Comment by HirbodBehnam** [comment]
They are working on a fake TLS connection. Hope that one work out.

**Comment by ParsDev** [comment]
> 
> 
> as I said, sometimes, IP has been banned. and Random Padding does NOT work at all
> 
> most of time you can find out by ping the IP
> if it works (wait till ping finish) then look for your configure problem

new format of filtering in Iran: only the proxy is inaccessible and we can be connected to the proxy server via the ssh :)

**Comment by HirbodBehnam** [comment]
Oh I haven't encountered this one.

**Comment by sahareh** [comment]
It seems there is a complex IP ban algorithms from Iran and you have to change IP address and this is not this repository's business.

**Comment by FreedomPrevails** [comment]
If you use random padding, it will not be detected by DPI systems. I have a private one shared by friends and family working for months.
But if it detected, your only solution is to change the IP address and wait for old one to be unblocked.

**Comment by Momenimahdi2** [comment]
i enable random padding but my vps ip was banned

‫‪FreedomPrevails‬‏ <‪notifications@github.com‬‏> در تاریخ سه‌شنبه ۳۰
ژوئیهٔ ۲۰۱۹ ساعت ۴:۰۵ نوشت:‬
