### ISSUE TITLE
[Important] Established connections don't close

### ISSUE THREAD

**Issue by hookzof** [TelegramMessenger/MTProxy#343]
Using the command `netstat -anp | grep :443 | grep ESTAB | wc -l` you can see that the established connections grow even at night, which should not happen. There are suggestions that this may be due to the peculiarities of DPI of different countries.

Measurements are taken every 3 hours.

```
root@stab:~# netstat -anp | grep :443 | grep ESTAB | wc -l
68472
root@stab:~# netstat -anp | grep :443 | grep ESTAB | wc -l
97860
root@stab:~# netstat -anp | grep :443 | grep ESTAB | wc -l
126076
```
![py6i6j](https://user-images.githubusercontent.com/22233835/65372604-0edd8f00-dc7b-11e9-93c0-6ff7a3345edd.png)

Only Fake TLS is used.

**Comment by kmurachev** [comment]
This command gives me the following:
```
# netstat -anp | grep :443 | grep ESTAB | wc -l
10
```
despite the fact that only six devices connect to my proxy (four of them are one account)

**Comment by hookzof** [comment]
I forgot to note that the proxy is public.

**Comment by kmurachev** [comment]
> I forgot to note that the proxy is public.

this is noticeable based on the number of connections)

**Comment by hookzof** [comment]
Possible fix https://github.com/TelegramMessenger/MTProxy/commit/b93e44b8616346d9c278bcc214c7a7671e8883a6
