### ISSUE TITLE
detecting blocked ip

### ISSUE THREAD

**Issue by maghorbani** [TelegramMessenger/MTProxy#350]
iran RDP blockes ip's so that just mtproxy packets will be blocked! i don't know how they're doing this!!
on a blocked ip, i stoped mtproxy service and made a simple web service on the same port, and it worked fine when i requested from iran!!!!!
so i want to know, is there any way to make a mtproxy request to the server and check if the ip is blocked of not!? the request should be exactly like the request that the telegram app makes.

**Comment by picohub** [comment]
Did you add dd prefix to your secret?

**Comment by WebShark025** [comment]
You can use this Telegram bot which is built to do this exact thing:
@ProxyTesterBot
The developer also provides an API for that.

**Comment by maghorbani** [comment]
> You can use this Telegram bot which is built to do this exact thing:
> @ProxyTesterBot
> The developer also provides an API for that.

Thank you! it works as well
