### ISSUE TITLE
Proxy sponsor with no docker

### ISSUE THREAD

**Issue by zandiarash** [TelegramMessenger/MTProxy#353]
Hello dear developers.
We are using windows server 2012 which doesn't support the docker.
Thus we have to use mtproto proxies like these :

dotnet => [https://github.com/freepvps/mtproto-proxy](https://github.com/freepvps/mtproto-proxy)
dotnet => [https://github.com/TGMTProto/MTProtoProxy/issues/20](https://github.com/TGMTProto/MTProtoProxy/issues/20)
NodeJS=> [https://github.com/MTProto/MTProtoProxy](https://github.com/MTProto/MTProtoProxy)
NodeJS=>  [https://github.com/sadra/EasyMTProto](https://github.com/sadra/EasyMTProto)
but none of these support the tag.

please do not leave thise line for me
`mtproto-proxy -u nobody -p 8888 -H 443 -S <secret>-P abc123xyz --aes-pwd proxy-secret proxy-multi.conf -M 1`
because seems the implementations are different from the docker.
is there a way to set the tag in an mtproto which doesn't use the docker like the above projects ?

**Comment by rlka** [comment]
mmmmm... docker and mtpoxy are 2 different things.
just should set your tag with -P ?

**Comment by zandiarash** [comment]
> 
> 
> mmmmm... docker and mtpoxy are 2 different things.
> just should set your tag with -P ?

Thanks for your answer,
Maybe I could not say what I mean correctly.
Yes I know that they are completely two different things.
But I've mentioned that we cannot use the **official** telegram MTPROTO which **uses the docker**.
Please show me a solution for **Unofficial** ones which **do not use the docker** and have different implementations like **.Net**, **python**, **php**, **Node.js** or etc to become channel sponsors.
Thanks again

**Comment by rlka** [comment]
Probably you mean MTProxy not for linux:) 
can't help you here

**Comment by zandiarash** [comment]
> Probably you mean MTProxy not for linux:)
> can't help you here

Dear Rlka the platform is not the matter.
The proxies which I mentioned works on the Linux also.
My question is this :
Is there a way to become channel sponsor with old MTPROTO proxies which are implemented before the telegram official MTPROTO?

**Comment by stek29** [comment]
it has nothing to do with this repo
