### ISSUE TITLE
Active session show my home ip-adress, not proxy ip

### ISSUE THREAD

**Issue by biobdeveloper** [TelegramMessenger/MTProxy#36]
I succesful run my MTProxy builded from source, I see "connected" in proxy settings and shield icon in Telegram Andoid interface. But I see that my device connected form my home IP in menu Active sessoins . Is it ok?

**Comment by seega** [comment]
yes, it's ok, this proxy passes your IP to the telegram server

**Comment by stek29** [comment]
https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/mtproto/mtproto-proxy.c#L1771-L1782
