### ISSUE TITLE
Stuck at main loop

### ISSUE THREAD

**Issue by miadabdi** [TelegramMessenger/MTProxy#366]
I follow [README.md](https://github.com/TelegramMessenger/MTProxy) but it gets stuck at main loop

`# ./mtproto-proxy --ipv6 -u nobody -p 8888 -H 443 -S 2df9886999c6ea3b1fb3e34a8c5593af --aes-pwd proxy-secret proxy-multi.conf -M 1`

`[325][2020-01-18 16:01:42.319179 local] Invoking engine mtproxy-0.01 compiled at Jan 18 2020 05:07:31 by gcc 4.9.2 64-bit after commit dc0c7f3de40530053189c572936ae4fd1567269b
[325][2020-01-18 16:01:42.360874 local] config_filename = 'proxy-multi.conf'
[325][2020-01-18 16:01:42.363258 local] creating 1 workers
[326][2020-01-18 16:01:42.410823 local] Started as [10.8.0.1:8888:326:1579359702]
[326][2020-01-18 16:01:42.411584 local] configuration file proxy-multi.conf re-read successfully (752 bytes parsed), new configuration active
[326][2020-01-18 16:01:42.416779 local] main loop
[325][2020-01-18 16:01:42.512677 local] Started as [10.8.0.1:8888:325:1579359702]
[325][2020-01-18 16:01:42.513839 local] configuration file proxy-multi.conf re-read successfully (752 bytes parsed), new configuration active
[325][2020-01-18 16:01:42.514189 local] main loop`

`# uname -a`
`Linux berbidvps 3.16.0-10-amd64 #1 SMP Debian 3.16.76-1 (2019-11-12) x86_64 GNU/Linux`
It is Debian jessie 64-bits VPS, on Hetzner.
It worth mentioning that i also run Openvpn on this VPS.

**Comment by ACERLZ** [comment]
I have met with the same issue, and I wonder how you solved it.
Please tell me your solution, thanks.

**Comment by ACERLZ** [comment]
> I follow [README.md](https://github.com/TelegramMessenger/MTProxy) but it gets stuck at main loop
> 
> `# ./mtproto-proxy --ipv6 -u nobody -p 8888 -H 443 -S 2df9886999c6ea3b1fb3e34a8c5593af --aes-pwd proxy-secret proxy-multi.conf -M 1`
> 
> `[325][2020-01-18 16:01:42.319179 local] Invoking engine mtproxy-0.01 compiled at Jan 18 2020 05:07:31 by gcc 4.9.2 64-bit after commit dc0c7f3de40530053189c572936ae4fd1567269b [325][2020-01-18 16:01:42.360874 local] config_filename = 'proxy-multi.conf' [325][2020-01-18 16:01:42.363258 local] creating 1 workers [326][2020-01-18 16:01:42.410823 local] Started as [10.8.0.1:8888:326:1579359702] [326][2020-01-18 16:01:42.411584 local] configuration file proxy-multi.conf re-read successfully (752 bytes parsed), new configuration active [326][2020-01-18 16:01:42.416779 local] main loop [325][2020-01-18 16:01:42.512677 local] Started as [10.8.0.1:8888:325:1579359702] [325][2020-01-18 16:01:42.513839 local] configuration file proxy-multi.conf re-read successfully (752 bytes parsed), new configuration active [325][2020-01-18 16:01:42.514189 local] main loop`
> 
> `# uname -a`
> `Linux berbidvps 3.16.0-10-amd64 #1 SMP Debian 3.16.76-1 (2019-11-12) x86_64 GNU/Linux`
> It is Debian jessie 64-bits VPS, on Hetzner.
> It worth mentioning that i also run Openvpn on this VPS.

I have met with the same issue, and I wonder how you solved it.
Please tell me your solution, thanks.
