### ISSUE TITLE
error on complie

### ISSUE THREAD

**Issue by Metal-Ghost** [TelegramMessenger/MTProxy#37]
~/5$ make
fatal: Not a git repository (or any of the parent directories): .git
cc -o objs/bin/mtproto-proxy objs/mtproto/mtproto-proxy.o objs/mtproto/mtproto-config.o objs/net/net-tcp-rpc-ext-server.o objs/lib/libkdb.a objs/lib/libkdb.a -m64 -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
objs/lib/libkdb.a(sha256.o): In function `sha256':
sha256.c:(.text+0xb6): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha256.o): In function `sha256_two_chunks':
sha256.c:(.text+0x120): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha256.o): In function `sha256':
sha256.c:(.text+0xee): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha256.o): In function `sha256_two_chunks':
sha256.c:(.text+0x16a): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(net-msg.o): In function `rwm_sha1':
net-msg.c:(.text+0x2da6): undefined reference to `EVP_MD_CTX_new'
net-msg.c:(.text+0x2ddd): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha1.o): In function `sha1':
sha1.c:(.text+0xb6): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha1.o): In function `sha1_two_chunks':
sha1.c:(.text+0x120): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha1.o): In function `sha1':
sha1.c:(.text+0xee): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha1.o): In function `sha1_two_chunks':
sha1.c:(.text+0x16a): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'objs/bin/mtproto-proxy' failed
make: *** [objs/bin/mtproto-proxy] Error 1

i when make see this error
i build other server and copy bin file here and when run i see error

mtproto-proxy: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by seega** [comment]
https://github.com/TelegramMessenger/MTProxy/commit/155e39dce5d036f46eb047ba6e5ea3934354242e 4 hours ago was fixed, your source updated?

**Comment by Metal-Ghost** [comment]
yea updated
man now builded but on run the mtproto-proxy
returned error 
mtproto-proxy: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

**Comment by seega** [comment]
try https://github.com/TelegramMessenger/MTProxy/issues/4#issuecomment-393310157

**Comment by Metal-Ghost** [comment]
thanks all fixed

**Comment by Metal-Ghost** [comment]
hi all how can stop the proxy?
its run in main loop and i close terminal
now how can close it?
