### ISSUE TITLE
Error on building 

### ISSUE THREAD

**Issue by erfanghobadian** [TelegramMessenger/MTProxy#4]
I tryed to build the app using make command
But reach the Error
![c57a992a-6fa9-47d1-9a78-7fd80f5dec02](https://user-images.githubusercontent.com/39496708/40736802-3f812496-6454-11e8-8b97-8e8b6aca4424.jpeg)

**Comment by madl-ash** [comment]
I have the same problem

**Comment by loskiq** [comment]
On Debian/Ubuntu: ```apt-get install zlib1g-dev```

**Comment by madl-ash** [comment]
@ioskiq still the same error on ubuntu server 16.04

**Comment by pecmapm** [comment]
+1

**Comment by Forst** [comment]
I think you need the `libssl-dev` package, since the referenced stuff is from OpenSSL.

**Comment by madl-ash** [comment]
if you dont add `libssl-dev` package the error is different,its says `openssl/(somefile).h is missing`
this happens after you install `libssl-dev` package

**Comment by pecmapm** [comment]
Ubuntu 16.04 openssl 1.1 instalation

openssl version

cd /usr/local/src
sudo wget https://www.openssl.org/source/latest.tar.gz -O openssl-1.1.0.tar.gz
sudo tar -zxvf openssl-1.1.0.tar.gz
cd openssl-1.1.0h/
sudo ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,-rpath,/usr/local/ssl/lib
sudo make && sudo make test
sudo make install
sudo mv /usr/bin/openssl /root/
sudo ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl

openssl version

**Comment by pecmapm** [comment]
@darkbyte-ru ubunti 16.04 installation openssl 1.1 did not help

**Comment by letnab** [comment]
+1
Error
```
objs/lib/libkdb.a(net-msg.o): In function `rwm_sha1':
net-msg.c:(.text+0x2e56): undefined reference to `EVP_MD_CTX_new'
net-msg.c:(.text+0x2e8d): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha256.o): In function `sha256':
sha256.c:(.text+0x86): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha256.o): In function `sha256_two_chunks':
sha256.c:(.text+0xf0): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha256.o): In function `sha256':
sha256.c:(.text+0xbe): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha256.o): In function `sha256_two_chunks':
sha256.c:(.text+0x13a): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha1.o): In function `sha1':
sha1.c:(.text+0x86): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha1.o): In function `sha1_two_chunks':
sha1.c:(.text+0xf0): undefined reference to `EVP_MD_CTX_new'
objs/lib/libkdb.a(sha1.o): In function `sha1':
sha1.c:(.text+0xbe): undefined reference to `EVP_MD_CTX_free'
objs/lib/libkdb.a(sha1.o): In function `sha1_two_chunks':
sha1.c:(.text+0x13a): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
make: *** [objs/bin/mtproto-proxy] Error 1
```
CentOS 7.5

**Comment by darkbyte-ru** [comment]
@pecmapm if you install openssl from source in different location (like /usr/local), so you need change Makefile and add "-I/usr/local/ssl/include/openssl/" to CFLAGS and "-L/usr/local/ssl/lib/" to LDFLAGS

**Comment by phantom-code** [comment]
You need to install openssl >= 1.1.0 to fix this issue.

**Comment by phantom-code** [comment]
If you don't provide a configuration script, it would be great if there will be dependencies listed in README.

**Comment by MasterGroosha** [comment]
Okay, so, Ubuntu 16.04 uses libssl version 1.0.* while MTProxy requires 1.1.*.
So I tried to install libssl version 1.1.0, using [this](https://techlist.top/upgrade-openssl-version-1-1-0-ubuntu-server) guide:

```bash
wget https://www.openssl.org/source/latest.tar.gz -O openssl-1.1.0.tar.gz
tar xf openssl-1.1.0.tar.gz
cd openssl-1.1.0.tar.gz
./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -Wl,-rpath,/usr/local/ssl/lib
make
make install
```

Then I delete old openssl binary and create a symlink to a new one:
```bash
mv /usr/bin/openssl /tmp
ln -s /usr/local/ssl/bin/openssl /usr/bin/openssl
```
then I execute `openssl version` and it says `1.1.0`. So I return to MTProxy and edit Makefile:
1) Add `-I/usr/local/ssl/include/openssl` to `CFLAGS` variable
2) Add `-L/usr/local/ssl/lib/` to `LDFLAGS` variable as mentioned by @phantom-code 

However I still have this:
```bash
objs/lib/libkdb.a(sha256.o): In function `sha256_starts':
sha256.c:(.text+0x5): undefined reference to `EVP_MD_CTX_init'
objs/lib/libkdb.a(sha1.o): In function `sha1_starts':
sha1.c:(.text+0x5): undefined reference to `EVP_MD_CTX_init'
objs/lib/libkdb.a(aesni256.o): In function `tg_ssl_aes_ctr128_crypt':
aesni256.c:(.text+0x4d0): undefined reference to `AES_ctr128_encrypt'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'objs/bin/mtproto-proxy' failed
make: *** [objs/bin/mtproto-proxy] Error 1
```

Any advice?

**Comment by phantom-code** [comment]
Removing openssl-devel helped to me on CentOS7.

**Comment by ysamtme** [comment]
`apt-get remove libssl-dev` after installing 1.1.0 and fixing editing Makefile helped on 17.10

**Comment by darkbyte-ru** [comment]
@MasterGroosha, ahh, sorry, I forgot about "-I/usr/local/ssl/include/" in CFLAGS.

**Comment by MasterGroosha** [comment]
@darkbyte-ru I added it and it does compile, but doesn't run: 
```
./mtproto-proxy: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
There must be some problem with my Makefile, seems that I forgot something

**Comment by darkbyte-ru** [comment]
@MasterGroosha, this will help:
ln -s /usr/local/ssl/lib/libcrypto.so.1.1 /usr/lib/libcrypto.so.1.1

**Comment by pecmapm** [comment]
fresh ubuntu installation

lsb_release -a
Description:	Ubuntu 16.04.4 LTS
Release:		16.04
Codename:		xenial


sudo apt-get install -y build-essential
sudo apt-get install -y zlib1g-dev
cd /usr/local/src
sudo git clone https://github.com/openssl/openssl
cd openssl
sudo ./config
sudo make
sudo make test
sudo make install

sudo ldconfig -v | grep ssl
openssl version

sudo git clone https://github.com/TelegramMessenger/MTProxy
cd MTProxy
sudo make

**Comment by MasterGroosha** [comment]
@darkbyte-ru bingo! Thanks a lot, at least now it starts without errors :)

**Comment by SlavikMIPT** [comment]
Solved on centos 7.5 with installing openssl 1.1.0 using this guide:
https://blacksaildivision.com/how-to-install-openssl-on-centos
results:
```
openssl version
OpenSSL 1.1.0h  27 Mar 2018
```
then edit Makefile, add:
```
CFLAGS = **-I/usr/local/openssl/include** -m64 -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
LDFLAGS = **-L /usr/local/openssl/lib** -m64 -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
```
```
make clean
make
```
enjoy

**Comment by Plz69** [comment]
Hi,

In the last step: 
`./mtproto-proxy -u nobody -p 8888 -H 443  ...`

I see this error:
`mtproto-proxy: net/net-tcp-rpc-client.c:246: tcp_rpcc_send_handshake_packet: Assertion `PID.ip' failed.`

http://uupload.ir/files/lgah_mtp.jpg

**Comment by SlavikMIPT** [comment]
@Plz69 Yes - you need to open this port in firewall
try to run it with sudo

**Comment by farshidlove** [comment]
Send mtproxy installation instructions to Sentus 7?

**Comment by farshidlove** [comment]
Send mtproxy installation instructions to cenots7?🌹

**Comment by farshidlove** [comment]
![screenshot_ -](https://user-images.githubusercontent.com/39788567/40775942-d746031e-64b8-11e8-8b4d-510730c43aa5.png)

Why is this reason when compiling because of what?
Please answer

**Comment by CerNerCompany** [comment]
sha1.c:(.text+0x156): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'objs/bin/mtproto-proxy' failed
make: *** [objs/bin/mtproto-proxy] Error 1
 why ?

**Comment by stek29** [comment]
Get latest sources with fix for OpenSSL 1.0.x.

**Comment by farshidlove** [comment]
Why are ip servers filtered for proxy? Can it be encrypted ?!

**Comment by toxi22** [comment]
Help is needed. I faced the same error.
OS: Debian GNU/Linux 11 (bullseye)
```
rm -f objs/lib/libkdb.a && ar rcs objs/lib/libkdb.a objs/common/crc32c.o objs/common/pid.o objs/common/sha1.o objs/common/sha256.o objs/common/md5.o objs/common/resolver.o objs/common/parse-config.o objs/crypto/aesni256.o objs/jobs/jobs.o objs/common/mp-queue.o objs/net/net-events.o objs/net/net-msg.o objs/net/net-msg-buffers.o objs/net/net-config.o objs/net/net-crypto-aes.o objs/net/net-crypto-dh.o objs/net/net-timers.o objs/net/net-connections.o objs/net/net-rpc-targets.o objs/net/net-tcp-connections.o objs/net/net-tcp-rpc-common.o objs/net/net-tcp-rpc-client.o objs/net/net-tcp-rpc-server.o objs/net/net-http-server.o objs/common/tl-parse.o objs/common/common-stats.o objs/engine/engine.o objs/engine/engine-signals.o objs/engine/engine-net.o objs/engine/engine-rpc.o objs/engine/engine-rpc-common.o objs/net/net-thread.o objs/net/net-stats.o objs/common/proc-stat.o objs/common/kprintf.o objs/common/precise-time.o objs/common/cpuid.o objs/common/server-functions.o objs/common/crc32.o
cc -o objs/bin/mtproto-proxy objs/mtproto/mtproto-proxy.o objs/mtproto/mtproto-config.o objs/net/net-tcp-rpc-ext-server.o objs/lib/libkdb.a objs/lib/libkdb.a  -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
/usr/bin/ld: objs/mtproto/mtproto-config.o:(.bss+0x200a0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/net/net-tcp-rpc-ext-server.o:(.bss+0x0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(resolver.o):(.bss+0x0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(parse-config.o):(.bss+0x28): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-rpc-targets.o):(.bss+0x820): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-http-server.o):(.bss+0x18): multiple definition of `http_queries'; objs/mtproto/mtproto-proxy.o:(.bss+0x488): first defined here
/usr/bin/ld: objs/lib/libkdb.a(engine-rpc.o):(.bss+0x0): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-stats.o):(.bss+0x8): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(pid.o):(.bss+0x0): multiple definition of `PID'; objs/lib/libkdb.a(net-stats.o):(.bss+0x30): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:94: objs/bin/mtproto-proxy] Error 1

```
```
root@vps-f9046aaf:~/MTProxy# openssl
OpenSSL> version
OpenSSL 1.1.1n  15 Mar 2022
OpenSSL> ^C

```
