### ISSUE TITLE
کسی میتونه وضعیت الان پراکسی هارو شرح بده؟

### ISSUE THREAD

**Issue by MobinS** [TelegramMessenger/MTProxy#412]
سلام اساتید خسته نباشید، شاید دارم جای درستی نمیپرسم ولی خب کجا بهتر :/ 
یکی دو روزه هیچ پراکسی ای رو ای دی اس ال کار نمیکنه قضیه چیه دقیقا؟؟

چه روش دور زدنی الان جوابه که فیلتر نشن(یا حداقل دو سه روز دووم بیارن)؟

**Comment by haminian99** [comment]
سلام فیلتر شکن ها کار می کنند و هم چنین پروکسی هااحتمال زیادپروکسی هاتون خوب نیستاین پروکسی رو تست کنید پروکسی سالم و مشکلی ندارد در صورت وصل نشدن مشکل از اینترنت شما هستserver=13.73.147.210port=443secret=eeeee4681112a6bb8198d9a435ab2a21c7646f776e6c6f61642e616e796465736b2e636f6dOn Jul 23, 2020 7:30 PM, MobinS <notifications@github.com> wrote:
سلام اساتید خسته نباشید، شاید دارم جای درستی نمیپرسم ولی خب کجا بهتر :/
یکی دو روزه هیچ پراکسی ای رو ای دی اس ال کار نمیکنه قضیه چیه دقیقا؟؟
چه روش دور زدنی الان جوابه که فیلتر نشن(یا حداقل دو سه روز دووم بیارن)؟

**Comment by MobinS** [comment]
ممنون تلگرام دسکتاپو ری اینستال کردم درست شد نفهمیدم مشکل از کجاست آخرش
