### ISSUE TITLE
Run MTProxy in Windows server

### ISSUE THREAD

**Issue by ehaidari** [TelegramMessenger/MTProxy#43]
How we can run **official** MTProxy on windows server 2012 R2?

**Comment by stek29** [comment]
Run the docket image.
Duplicate of at least two other issues.

**Comment by Metal-Ghost** [comment]
hi if you can.
install VMWare 12 and install ubuntu and try to run MTProto-Proxy

**Comment by seega** [comment]
@ehaidari https://github.com/TelegramMessenger/MTProxy/issues/5#issuecomment-393505406

**Comment by mr-459** [comment]
y78i78
docker not may
at docker you get errore: you cant run linux prodects under windows
