### ISSUE TITLE
How to setup on Microsoft azure?

### ISSUE THREAD

**Issue by mrbaranovskiy** [TelegramMessenger/MTProxy#44]
I've configured and ran the agent under ubuntu server but cannot access through the proxy. Probably there should be some additional port rules or smth like that...

**Comment by loskiq** [comment]
Create a new virtual machine. Desirable is Debian 9. Then follow the instructions of README.

**Comment by mrbaranovskiy** [comment]
Yes, I've done all of that. Agent works. I can event psping shows that 443 is responsive when the agent runs. (to do that I've disabled the inbound and outbound rules for the ports.)  

When I setup the proxy for the desktop app - "Connecting" infinite. 

I'll play around...

**Comment by raccoon4x** [comment]
same problems. =(
but php version by **danogentili** worked

**Comment by stek29** [comment]
Maybe Azure has some settings for ipv4 forwarding too? (see https://github.com/TelegramMessenger/MTProxy/issues/39#issuecomment-393825178)

**Comment by mrbaranovskiy** [comment]
IP forwarding doesn't help.

**Comment by mrbaranovskiy** [comment]
I'm stupid... 
az vm open-port --resource-group <myResourceGroup> --name <myVM> --port 443 

just execute this.

**Comment by ram3ai** [comment]
Adding `--nat-info private_ip:public_ip` helped in my case.
