### ISSUE TITLE
How to add my proxy to MTProto Proxies channel ?

### ISSUE THREAD

**Issue by albabosh** [TelegramMessenger/MTProxy#45]
How to add my proxy to MTProto Proxies channel ?

**Comment by seega** [comment]
@albabosh Contact the channel administrator, which channel are you talking about?

**Comment by MasterGroosha** [comment]
Your question is unrelated to this repository. There are no official channels about with MTProto proxies. The only official thing for now (an as far as I see as a regular user) is [@MTProxybot](https://t.me/mtproxybot)

**Comment by Metal-Ghost** [comment]
hi all
i run it
will try to share here on in channel [@VPN_And_Proxies](http://t.me/VPN_And_Proxies)
[Sponsor Tested MTPP link](https://t.me/proxy?server=88.99.220.156&port=4545&secret=935ddceb2f6bbbb78363b224099f75c8)

**Comment by MasterGroosha** [comment]
@Metal-Ghost I'm afraid your blatant advertising isn't good for this repo.

**Comment by Metal-Ghost** [comment]
@MasterGroosha Why?

**Comment by Metal-Ghost** [comment]
@seega man its test :| (i choose a low host for test only and its work)
ok
for run sponsor channel start the bot [@MTProxybot](t.me/MTProxybot)
send command /newproxy
now send your host ip and port
host:port
example:
56.125.35.41:443
now need a secret 
generate a secret or send a secret
to generate use code
head -c 16 /dev/urandom | xxd -ps
on windows use [C#](https://github.com/Metal-Ghost/MTPProxy/releases) Program
now send /myproxies code to bot
now choose you proxy
now click on set promotion
now send channel id for this 
the bot send a Tag for you after create new proxy
now go to run this proxy with sponsor
go terminal and use command :
mtproto-proxy -u USERNAME -p LOCALPORT -H PUBLICPORT -S SECRET -P TAG --aes-pwd proxy-secret proxy-multi.conf -M 1
Where : 
              - USERNAME is the user name. mtproto-proxy calls setuid() to drop privilegies
              - LOCALPORT  a local port for run proxy on the server
              - PUBLICPORT a public port you used in telegram proxy to connect
              - SECRET a secret for confirm you telegram
              - TAG is the tag the telegram bot send to you
and done!
if you connect proxy sponsor channel showing and you can not delete this
for need stats of you proxy use the stats button
 Good Luck all and like this not down :)

**Comment by stek29** [comment]
Also see #14 on why there's no official channel
