### ISSUE TITLE
It will be dead after running several weeks and can not restart the program but only reboot the server

### ISSUE THREAD

**Issue by CCCAUCHY** [TelegramMessenger/MTProxy#481]

**Comment by Electerocode** [comment]
Or the server is filtered
or should
screen
Take it so that it does not turn off

**Comment by alexdatur** [comment]
Same issue. Can somebody help?

**Comment by alexdatur** [comment]
> _No description provided._

How you solve this problem?

**Comment by CCCAUCHY** [comment]
> 

Made the PID of MTProxy less than 65535

**Comment by CCCAUCHY** [comment]
> > _No description provided._
> 
> How you solve this problem?

Made the PID of MTProxy less than 65535
