### ISSUE TITLE
MTProxy does not compile and run under Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by cgicoffee** [TelegramMessenger/MTProxy#484]
Hi,

If you stil maintain this repo, please look into this. Trying to `make` under Ubuntu 22.04.1 LTS (server) fails (clean install from the downloaded sources) with this log:

```
cc -o objs/bin/mtproto-proxy objs/mtproto/mtproto-proxy.o objs/mtproto/mtproto-config.o objs/net/net-tcp-rpc-ext-server.o objs/lib/libkdb.a objs/lib/libkdb.a  -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
/usr/bin/ld: objs/mtproto/mtproto-config.o:(.bss+0x200a0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/net/net-tcp-rpc-ext-server.o:(.bss+0x0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(resolver.o):(.bss+0x0): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(parse-config.o):(.bss+0x28): multiple definition of `kdb_hosts_loaded'; objs/mtproto/mtproto-proxy.o:(.bss+0x4f01b48): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-rpc-targets.o):(.bss+0x820): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-http-server.o):(.bss+0x18): multiple definition of `http_queries'; objs/mtproto/mtproto-proxy.o:(.bss+0x488): first defined here
/usr/bin/ld: objs/lib/libkdb.a(engine-rpc.o):(.bss+0x0): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(net-stats.o):(.bss+0x8): multiple definition of `total_vv_tree_nodes'; objs/lib/libkdb.a(net-connections.o):(.bss+0xc34a8): first defined here
/usr/bin/ld: objs/lib/libkdb.a(pid.o):(.bss+0x0): multiple definition of `PID'; objs/lib/libkdb.a(net-stats.o):(.bss+0x30): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:94: objs/bin/mtproto-proxy] Error 1
```

Required dependencies installed and exist in the system (`sudo apt install git curl build-essential libssl-dev zlib1g-dev`)

Previously compiled binaries that worked under Ubuntu 20.04 LTS fail to start as well.

Please advise.

**Comment by pursultani** [comment]
This is because of GCC 11. Add `-fcommon` to `CFLAGS` and `LDFLAGS` and it should be fine:

```diff
diff --git a/Makefile b/Makefile
index 67e6771..913e10b 100644
--- a/Makefile
+++ b/Makefile
@@ -12,8 +12,8 @@ ifeq ($m, 64)
 ARCH = -m64
 endif
 
-CFLAGS = $(ARCH) -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
-LDFLAGS = $(ARCH) -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
+CFLAGS = $(ARCH) -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -fcommon -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
+LDFLAGS = $(ARCH) -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto -fcommon
 
 LIB = ${OBJ}/lib
 CINCLUDE = -iquote common -iquote .
```

**Comment by cgicoffee** [comment]
**Thank you!** I re-downloaded the sources, changed the makefile and was able to successfully compile and run it.

**Comment by rezaparsad** [comment]
> This is because of GCC 11. Add `-fcommon` to `CFLAGS` and `LDFLAGS` and it should be fine:
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index 67e6771..913e10b 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -12,8 +12,8 @@ ifeq ($m, 64)
>  ARCH = -m64
>  endif
>  
> -CFLAGS = $(ARCH) -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
> -LDFLAGS = $(ARCH) -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
> +CFLAGS = $(ARCH) -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -fcommon -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
> +LDFLAGS = $(ARCH) -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto -fcommon
>  
>  LIB = ${OBJ}/lib
>  CINCLUDE = -iquote common -iquote .
> ```

I did this, but the proxy-multiple.conf file and the proxy-secret file were not created

**Comment by FranLopezZ** [comment]
> 
> I did this, but the proxy-multiple.conf file and the proxy-secret file were not created

@rezaparsad 
You need to get them manually from telegram page:

1. Obtain a secret, used to connect to telegram servers.
```bash
curl -s https://core.telegram.org/getProxySecret -o proxy-secret
```

2. Obtain current telegram configuration. It can change (occasionally), so we encourage you to update it once per day.
```bash
curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf
```


**Source**: [https://github.com/TelegramMessenger/MTProxy?tab=readme-ov-file#running](https://github.com/TelegramMessenger/MTProxy?tab=readme-ov-file#running)
