### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by MTO50** [TelegramMessenger/MTProxy#5]
Does it work on Windows?

**Comment by stek29** [comment]
It only works on Linux since it relies on features like epoll which are only available on Linux.

Getting it to work on *BSDs and adding kqueue based async handling shouldn’t be too hard, unlike porting it to windows and IOCP.

**Comment by arashmm50** [comment]
@stek29 This is very bad. I do not know why the telegram uses this kind of programmers

**Comment by temporaryaccount** [comment]
@arashmm50 

Because they know that no sane person uses a Windows server these days, maybe except the financial sector who are stuck with regulations and certified software stacks.

**Comment by seega** [comment]
@arashmm50 
try https://www.docker.com/docker-windows
requirements: windows with hyper-v (win pro/enterprise , win server), cpu with full hyper-v support

**Comment by arashmm50** [comment]
@temporaryaccount This is not true
@seega I will try

**Comment by MTO50** [comment]
@seega How can I run a proxy in Docker? How to compile?

**Comment by seega** [comment]
@MTO50 https://hub.docker.com/r/telegrammessenger/proxy/
