### ISSUE TITLE
vless://96d22529-b92a-40de-86c2-591d195a2d55@mtn.MsV2ray.space:2083?mode=gun&security=tls&encryption=none&type=grpc&serviceName=@MsV2ray&sni=tm.MsV2ray.cfd#%40VpnProSec+%7C+Mtn

### ISSUE THREAD

**Issue by Hamedkamrava** [TelegramMessenger/MTProxy#510]

**Comment by amirramzan55** [comment]
https://github.com/TelegramMessenger/MTProxy/issues/510#issue-1745119495

**Comment by amirramzan55** [comment]
dmxlc3M6Ly9mMjFiYmJmZS00M2EyLTQ4MzctYTczYS0yMzg0YzhlZTc2YmJAYWxsLnZwbmN1c3RvbWl6ZS5jYW06MjA5Nj9tb2RlPWd1biZzZWN1cml0eT10bHMmZW5jcnlwdGlvbj1ub25lJmZwPXNhZmFyaSZ0eXBlPWdycGMmc2VydmljZU5hbWU9QFZQTkNVU1RPTUlaRSZzbmk9Q2FOTmVjdFYycmF5LU9ubHlJUkFOLW1DaS1pcmFyYWNuenNrLXJndC1ta2gudmFyemVzaDMtQ0ROLnNpdGUjJURBJTg2JUQ5JTg2JUQ5JTg0KyVEOSU4NSVEOCVBNyVGMCU5RiU5MSU4OCVGMCU5RiU5MSU4OEdIX3YycmF5bmclNDA=

**Comment by amirramzan55** [comment]
amirramzan55

**Comment by amirramzan55** [comment]
Amirramzan55

**Comment by amirramzan55** [comment]
@amirramzan55
