### ISSUE TITLE
pointer targets in passing argument 2 of ‘__get_cpuid’ differ in signedness [-Wpointer-sign]

### ISSUE THREAD

**Issue by FreedomPrevails** [TelegramMessenger/MTProxy#59]
#uname -a
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

In file included from common/cpuid.c:21:0:
common/cpuid.c: In function ‘kdb_cpuid’:
common/cpuid.c:36:25: warning: pointer targets in passing argument 2 of ‘__get_cpuid’ differ in signedness [-Wpointer-sign]
   assert(__get_cpuid(1, &a, &cached.ebx, &cached.ecx, &cached.edx) != 0);
                         ^
In file included from common/cpuid.c:22:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/cpuid.h:237:1: note: expected ‘unsigned int *’ but argument is of type ‘int *’
 __get_cpuid (unsigned int __leaf,
 ^~~~~~~~~~~
In file included from common/cpuid.c:21:0:
common/cpuid.c:36:29: warning: pointer targets in passing argument 3 of ‘__get_cpuid’ differ in signedness [-Wpointer-sign]
   assert(__get_cpuid(1, &a, &cached.ebx, &cached.ecx, &cached.edx) != 0);
                             ^
In file included from common/cpuid.c:22:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/cpuid.h:237:1: note: expected ‘unsigned int *’ but argument is of type ‘int *’
 __get_cpuid (unsigned int __leaf,
 ^~~~~~~~~~~
In file included from common/cpuid.c:21:0:
common/cpuid.c:36:42: warning: pointer targets in passing argument 4 of ‘__get_cpuid’ differ in signedness [-Wpointer-sign]
   assert(__get_cpuid(1, &a, &cached.ebx, &cached.ecx, &cached.edx) != 0);
                                          ^
In file included from common/cpuid.c:22:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/cpuid.h:237:1: note: expected ‘unsigned int *’ but argument is of type ‘int *’
 __get_cpuid (unsigned int __leaf,
 ^~~~~~~~~~~
In file included from common/cpuid.c:21:0:
common/cpuid.c:36:55: warning: pointer targets in passing argument 5 of ‘__get_cpuid’ differ in signedness [-Wpointer-sign]
   assert(__get_cpuid(1, &a, &cached.ebx, &cached.ecx, &cached.edx) != 0);
                                                       ^
In file included from common/cpuid.c:22:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/cpuid.h:237:1: note: expected ‘unsigned int *’ but argument is of type ‘int *’
 __get_cpuid (unsigned int __leaf,
 ^~~~~~~~~~~

**Comment by stek29** [comment]
Thanks

**Comment by sadehg1378** [comment]
سلام کسی میتونه واسه ساخت پروکسی اینجا کمکم کنه بیاد پی وی تلگرامم @si_n_gl
