### ISSUE TITLE
Cannot raise open file limit to 65552

### ISSUE THREAD

**Issue by ElijahReva** [TelegramMessenger/MTProxy#60]
Hello!

I run into issues with MTProxy running on Docker on CentOS cloud VM. When I'm trying to start docker container, it goes into the endless loop of restarts. Docker logs show next error.

```
failed to set rlimit for open files. Try running as root or requesting smaller maxconns value.
fatal: cannot raise open file limit to 65552
```

What is the right way to set MAX_CONNECTIONS value when running Docker container?

My setup:
```
Virtualization: kvm
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-862.2.3.el7.x86_64
Architecture: x86-64
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by stek29** [comment]
Use `--connections` / `-c` command line argument to override default `MAX_CONNECTIONS`.

**Comment by sh-valery** [comment]
Alternatively just increase the limits with  `--ulimit` flag

```shell
docker run -d -p 443:443 \
--ulimit nofile=131072:131072 \
-v proxy-config:/data \
-e SECRET=$secret \
--name=mtproto-proxy \
telegrammessenger/proxy:latest
```
