### ISSUE TITLE
Can I deploy a private MTPROTO proxy server on my vps?

### ISSUE THREAD

**Issue by VahidPY** [TelegramMessenger/MTProxy#67]
Hi everybody,
I wonder why in **step 6** of running mtproto-proxy, needs registering the proxy server.
Can I ignore this step? If it is necessary, does telegram make it public to other users? I see many proxy servers on MTPROTOproxies channel, but I want to create one for myself. How is it possible?

**Comment by riot26** [comment]
You can completely ignore step 6 if you don't need to set promotion channel or get stats from bot. AFAIK there are no any official proxy list or aggregation or something. Channels like MTPROTOproxies are unofficial and contributed by community.
