### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by Metal-Ghost** [TelegramMessenger/MTProxy#71]
i run mtpp on 4545 or 7070 and while try to connect the proxy can not connect this on telegram 
(mtpp return main loop)

**Comment by stek29** [comment]
#34 maybe?

**Comment by Metal-Ghost** [comment]
yea i try re run i install openssl
now error
[1294][2018-06-05 08:17:02.527748 local] main loop
mtproto-proxy: net/net-tcp-rpc-client.c:246: tcp_rpcc_send_handshake_packet: Assertion `PID.ip' failed.
[pid 1293] [time 1528179422]
------- Stack Backtrace -------
mtproto-proxy(print_backtrace+0x29)[0x444249]
mtproto-proxy(extended_debug_handler+0x10)[0x4443d0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f7aefe65390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f7aefabf428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f7aefac102a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7)[0x7f7aefab7bd7]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7f7aefab7c82]
mtproto-proxy[0x436675]
mtproto-proxy(cpu_tcp_server_reader+0x146)[0x4340f6]
mtproto-proxy(cpu_server_read_write+0xb)[0x42b00b]
mtproto-proxy(do_connection_job+0xca)[0x42d86a]
mtproto-proxy(unlock_job+0x29b)[0x41cfeb]
mtproto-proxy(run_pending_main_jobs+0x62)[0x41dc12]
mtproto-proxy(default_engine_server_start+0x145)[0x43edc5]
mtproto-proxy(default_main+0x1a3)[0x43f493]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f7aefaaa830]
mtproto-proxy(_start+0x29)[0x40fd69]
[pid 1293] [time 1528179422] -------------------------------
[pid 1293] [time 1528179422] mtproxy-0.01 compiled at Jun  2 2018 13:36:20 by gcc 4.9.4 64-bit after commit 842f343decf6c463bdecf1862e357c4a03e4bc97[pid 1293] [time 1528179422]
root@ip241:~# mtproto-proxy: net/net-tcp-rpc-client.c:246: tcp_rpcc_send_handshake_packet: Assertion `PID.ip' failed.
[pid 1294] [time 1528179422]
------- Stack Backtrace -------
mtproto-proxy(print_backtrace+0x29)[0x444249]
mtproto-proxy(extended_debug_handler+0x10)[0x4443d0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f7aefe65390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f7aefabf428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f7aefac102a]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7)[0x7f7aefab7bd7]
/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82)[0x7f7aefab7c82]
mtproto-proxy[0x436675]
mtproto-proxy(cpu_tcp_server_reader+0x146)[0x4340f6]
mtproto-proxy(cpu_server_read_write+0xb)[0x42b00b]
mtproto-proxy(do_connection_job+0xca)[0x42d86a]
mtproto-proxy(unlock_job+0x29b)[0x41cfeb]
mtproto-proxy(run_pending_main_jobs+0x62)[0x41dc12]
mtproto-proxy(default_engine_server_start+0x145)[0x43edc5]
mtproto-proxy(default_main+0x1a3)[0x43f493]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f7aefaaa830]
mtproto-proxy(_start+0x29)[0x40fd69]
[pid 1294] [time 1528179422] -------------------------------
[pid 1294] [time 1528179422] mtproxy-0.01 compiled at Jun  2 2018 13:36:20 by gcc 4.9.4 64-bit after commit 842f343decf6c463bdecf1862e357c4a03e4bc97[pid 1294] [time 1528179422]
