### ISSUE TITLE
Child * terminated, aborting

### ISSUE THREAD

**Issue by Dragon-Knight** [TelegramMessenger/MTProxy#72]
Hello.
At me a problem, - as soon as the client is connected, the program at once falls:
> [19554][2018-06-03 16:59:58.862012 local] Invoking engine mtproxy-0.01 compiled at Jun  3 2018 15:30:33 by gcc 4.9.2 64-bit after commit cdd348294d86e74442bb29bd6767e48321259bec
> [19554][2018-06-03 16:59:58.875438 local] config_filename = 'proxy-multi.conf'
> [19554][2018-06-03 16:59:58.876020 local] creating 1 workers
> [19554][2018-06-03 16:59:58.881622 local] Started as [10.0.0.11:18888:19554:1528034398]
> [19555][2018-06-03 16:59:58.881638 local] Started as [10.0.0.11:18888:19555:1528034398]
> [19554][2018-06-03 16:59:58.882364 local] configuration file proxy-multi.conf re-read successfully (797 bytes parsed), new configuration active
> [19555][2018-06-03 16:59:58.882368 local] configuration file proxy-multi.conf re-read successfully (797 bytes parsed), new configuration active
> [19554][2018-06-03 16:59:58.882560 local] main loop
> [19555][2018-06-03 16:59:58.882571 local] main loop
> [19554][2018-06-03 17:00:00.009401 local] Child 19555 terminated, aborting

Launch parameters:
> ./mtproto-proxy --http-ports 1443 --slaves 1 --proxy-tag $TAG --mtproto-secret $SECRET --log mtproto-proxy.log --port 18888 --user nobody --aes-pwd proxy-secret.conf proxy-multi.conf --crc32c

What can be wrong?

**Comment by ilyaroot** [comment]
Got this behaviour, when running MTProto proxy at home server in Moscow. I think, proxy gets terminated because it can't reach Telegram datacenter IP's because of blocking Telegram in Russia. So , you should run proxy at independent VPS with non-restricted access to all Internet.

**Comment by Dragon-Knight** [comment]
О, Русские, хота дя, тут только и сидеть из России :)
Суть в том, что мой провайдер игнорирует все запреты РКН и телеграм у меня работает без проблем, но я попробую запустить на VPS'ке.

**Comment by L11R** [comment]
@Dragon-Knight no, there are still many Iranians and other nations, so please, use English here and in other GitHub projects.
