### ISSUE TITLE
Proxies blocked in Iran in few hours or less

### ISSUE THREAD

**Issue by FreedomPrevails** [TelegramMessenger/MTProxy#73]
I am done running mtproto proxies until Telegram changes the encryption to TLS or makes them undetectable by random padding (if it works).
Some proxies last less than 1 hour now.
I recommend everyone in Iran to stop spreading mtproro proxies because they makes users more frustrated and angry.
Using a TLS based VPN like OpenConnect or Cisco Anyconnect is much more comfortable and user friendly and guess what ? It cant be detected and blocked.
Telegram really fucked up by this design.

**Comment by seega** [comment]
You can buy vpn for all Iranian users, whats ur problem?

**Comment by VahidPY** [comment]
I thought this protocol packet looks like HTTPS packet, so no one can distinguish them from other regular HTTPS packets. If I wasn't wrong, the only way they can do is blocking IP addresses, which is inevitable for all protocols work on the net. But this protocol makes some difficulties for government to ban each IP addresses manually. they block some protocols with their patterns, no matter which IP address is used but cannot do the same for this proxy. If you meant they know IP addresses simply and block all of them, I think it won't be continued for a long time, just first days they do all they can to make users disappointed.
But I think you mentioned another problem that I couldn't get it clearly. Could you clarify what's its problem?
OpenConnect, AnyConnect, OpenVPN, etc. all needs buying accounts or if a server is public, it can be banned like other protocols. So the only way to resist from IP blocking is to run your own server with mtproto proxy.

**Comment by VahidPY** [comment]
Ok, I got the answer from [#35](https://github.com/TelegramMessenger/MTProxy/issues/35)

I hope telegram have a plan for it

**Comment by FreedomPrevails** [comment]
@stek29 Do you have any updates regarding this issue ? is Telegram going to do anything about it ? I wonder why it is taking this long, we need changes at mtproto proxy clients and mtproto proxy servers. There is no change required on Telegram infrastructure.

**Comment by stek29** [comment]
@FreedomPrevails I'm not related to "official" Telegram, I do not know what their plans are, and I'm not working for Telegram -- I'm just a volunteer.
