### ISSUE TITLE
Proxy-multi.conf

### ISSUE THREAD

**Issue by mro0t** [TelegramMessenger/MTProxy#77]
Hi
 I try to run this with command
 
./mtproto-proxy -u iau -p 8888 -H 443 -S d73259fed234c5bbd6ed7479846ffa2f --aes-pwd proxy-secret proxy-multi.conf -M 1
 And show this error:
Jun  4 2018 04:55:28 by gcc 6.4.0 20180123 64-bit after commit cdd348294d86e74442bb29bd6767e48321259bec
[27417][2018-06-04 05:28:16.114132 local] config_filename = 'proxy-multi.conf'
[27417][2018-06-04 05:28:16.114149 local] cannot re-read config file proxy-multi.conf: No such file or directory
config check failed! (code -1)

What can i do?

**Comment by d0tfile** [comment]
@mro0t i think you missed some steps from manual: `curl -s https://core.telegram.org/getProxyConfig -o proxy-multi.conf` ([README](https://github.com/TelegramMessenger/MTProxy/blob/master/README))

**Comment by Vitamin1978** [comment]
curl -s https://core.telegram.org/getProxySecret -o proxy-secret
I`ve done so. But don`t get the proxy-secret.
Cause i live in Russia and telegram.org is blocked. I think that is the problem is.
 proxy-multi.conf i`ve added manualy. But with the proxy-secret i don`t know what to do. I need help.
Thank you.

**Comment by jamesfirstv** [comment]
Why you need proxy-secret if you have no connection? First of all you need VPN.

Дружище, прокси не заработает без видимости сети ТОН. Нужно сначала обеспечить видимость, например, через VPN, а там у тебя и файло само качнётся

**Comment by Vitamin1978** [comment]
Да. Все верно. Тор помог с файлом. Но не решил остальных проблем. Спасибо за помощь. Но от идеи запустить его дома придется отказаться.

**Comment by jamesfirstv** [comment]
Ни в коем случае не стоит отказываться от того, что можешь сделать сам.

Раз вы здесь, значит у вас есть Linux хост. На этом хосте вы можете использовать или openvpn (даст виртуальную сетевуху без блокировок), или socks5 proxy (даст подключение для конкретной проги, в вашем случае для MTProxy). Дальше, вопрос только в том, кто ваш сообщник за занавесом (например, другой ваш хостинг с openvpn-сервером или dante socks proxy server)

**Comment by Vitamin1978** [comment]
Спасибо за добрые слова. Я имел ввиду дома. Я уже занялся aws Amazon. Все будет хорошо, я думаю.
