### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by hamid07ss** [TelegramMessenger/MTProxy#80]
Hi!

i run this source code in a server (2G memory).
and now 200 person are using this proxy and when I try to connect to proxy, proxy stay in `connecting...` mode.
but some times connection and speed is so good!!

my server memory usage is:
![image](https://user-images.githubusercontent.com/17006865/40923318-c24f2bba-6829-11e8-8c37-ea9c67919a5d.png)

where is the problem?

**Comment by ashpooljh** [comment]
Have you tried increasing the number of workers (`-M option`)? What is your current number?

**Comment by iqdoctor** [comment]
check netstat on server side, of many sockets in SYN_RECV - this is new type of ISP traffic block in Russia.

**Comment by mortazakiyani** [comment]
hi how i  can manage too many connection in my proxy?
i have 2 gig Ram that 1 gig is free and my CPU work 23% 
but ping of proxy is 1500 and very low load speed in client..
Cent OS 7 ..
