### ISSUE TITLE
Error on the make command

### ISSUE THREAD

**Issue by naweed1998** [TelegramMessenger/MTProxy#81]
This is the error:
`root@s ~/MTProxy # make
cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"580909cbca12a2f8529dbb387edf8e9bc5bd4e3a\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
make: cc: Command not found
Makefile:86: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 127`

**Comment by p1ratrulezzz** [comment]
Apt-get install build-essential libssl-dev Lib1g-dev

**Comment by naweed1998** [comment]
`root@s ~ # apt-get install build-essential libssl-dev Lib1g-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package Lib1g-dev
root@s ~ #`
it doesn't install :(

**Comment by p1ratrulezzz** [comment]
apt-get install libssl-dev zlib1g-dev build-essential

Sorry misspelled second lib
