### ISSUE TITLE
problem in running the proxy

### ISSUE THREAD

**Issue by laknes** [TelegramMessenger/MTProxy#82]
bash: mtproto-proxy: command not found

where is the problem

**Comment by VahidPY** [comment]
After `make` source code, change current directory to objs/bin:
cd objs/bin/
then run mtproto-proxy:
./mtproto-proxy ...

Don't forget put "./" before mtproto-proxy

**Comment by laknes** [comment]
Thanks you I just found this solution before you tell but still I have
fucking problem with launching it
Vahid are you Iranian?

**Comment by rozbeh98** [comment]
hi can learn me how to use  make 
i have problem  [** no target ...]
tnx
