### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by gyutw** [TelegramMessenger/MTProxy#83]
I got this error in Ubuntu 16, any idea how to fix it?

cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"580909cbca12a2f8529dbb387edf8e9bc5bd4e3a\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
make: cc: Command not found
Makefile:86: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 127

**Comment by xray108** [comment]
apt-get install build-essential

**Comment by gyutw** [comment]
Thank you, now I get this:


cc  -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"580909cbca12a2f8529dbb387edf8e9bc5bd4e3a\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64 -iquote common -iquote . -c -MP -MD -MF dep/mtproto/mtproto-proxy.d -MQ objs/mtproto/mtproto-proxy.o -o objs/mtproto/mtproto-proxy.o mtproto/mtproto-proxy.c
mtproto/mtproto-proxy.c:42:26: fatal error: openssl/rand.h: No such file or directory
compilation terminated.
Makefile:86: recipe for target 'objs/mtproto/mtproto-proxy.o' failed
make: *** [objs/mtproto/mtproto-proxy.o] Error 1

**Comment by p1ratrulezzz** [comment]
Install libssl-dev and zlib1g-dev

**Comment by xray108** [comment]
#42

**Comment by gyutw** [comment]
Installed them as well, ran make and ran this:
 mtproto-proxy -u nobody -p 8888 -H 443 -S XXXXXXXXXXXXXXXXX --aes-pwd proxy-secret proxy-multi.conf -M 1
mtproto-proxy: command not found


Result:
mtproto-proxy: command not found

**Comment by mgdz** [comment]
you can find mtproto-proxy exetutable in objs/bin/

**Comment by gyutw** [comment]
I am in the directory:

root@ip251:~/MTProxy/objs/bin# pwd
/home/rootuser/MTProxy/objs/bin

root@ip251:~/MTProxy/objs/bin# mtproto-proxy -u nobody -p 8888 -H 443
-S xxxxxxxxxxxxxxxxxxxxxxxx --aes-pwd proxy-secret proxy-multi.conf -M
1
mtproto-proxy: command not found

**Comment by mgdz** [comment]
./mtproto-proxy -u nobody -p 8888 -H 443
-S xxxxxxxxxxxxxxxxxxxxxxxx --aes-pwd proxy-secret proxy-multi.conf -M
1

**Comment by p1ratrulezzz** [comment]
Please stop creating issues that actually are not issues at all. Problems like that can be solved by googling it. Or at least close issue and keep commenting in closed issue. The developer won't see REAL issues because of this gurbage
