### ISSUE TITLE
Run on multiple ports

### ISSUE THREAD

**Issue by james12974** [TelegramMessenger/MTProxy#84]
How i can run on muliple ports with tags?
i ran it on a port and then i tried to run on another port that said port 8888 is already in use

**Comment by SimWhite** [comment]
Running `mproto-proxy --help` will show the following:
`--http-ports/-H <arg>              	comma-separated list of client (HTTP) ports to listen`
So `mtproto-proxy -H 443,8443` will run proxy on 443 and 8443 ports.

**Comment by james12974** [comment]
yes but i cant see stats in bot

**Comment by SimWhite** [comment]
You already have something on 8888 port. Read the help and change port 8888 to something else.

**Comment by james12974** [comment]
so can i have stats for 2 ports?

**Comment by SimWhite** [comment]
You can run two instances with the different anything: ports, tags, secrets and so on.

**Comment by james12974** [comment]
sorry
i changed 8888 but bot did not give me any stats :(
but sponsor channel is ok

**Comment by p1ratrulezzz** [comment]
Just use dnat in iptables to forward all input traffic on interface eth0 (example) and port 1234 with --redirect --to-ports 1235 .for me it worked well enough.

**Comment by NightMachinary** [comment]
@p1ratrulezzz Can you give the complete command? I tried `iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to 8833` and `sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port 8833` but they didn't work.

**Comment by NightMachinary** [comment]
@james12974 How to use this `-H` from the docker?

**Comment by NightMachinary** [comment]
The best option is to simply use multiple `-pPORT:443` options. 😐😂

**Comment by p1ratrulezzz** [comment]
For port redirect: 

```bash
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 6968
```

That should do the job, but yes, you also can use multiple port options in -H

```
mtproto-proxy -H 443,6968
```

**Comment by shadowlmd** [comment]
Please close this issue.
