### ISSUE TITLE
Can not connect via DSL connection

### ISSUE THREAD

**Issue by Azaaaad** [TelegramMessenger/MTProxy#86]
Hi. Im in Iran. I can connect easily to most of mtproto proxies via 4g and 3g, but when i need to connect via DSL 90% of proxies with different ports cant work. The proxies stay on checking. Any solution?

**Comment by Reznovv** [comment]
they're are detecting mtproto proxy servers and block their ip's!
I don't know if they are doing this automatically or they just search the whole telegram. We cant do anything.
Need an update for making it Unblockable.

**Comment by Azaaaad** [comment]
Im almost aure that they haven't blocked my ip. I only myself know the ip. Also if they want to block, block in whole the network, not only DSL.

**Comment by Kolahzary** [comment]
Try updating your TDesktop, I had the same problem and it was solved after updating

**Comment by Azaaaad** [comment]
I have this problem on android client.

**Comment by Kolahzary** [comment]
Try changing port on server(some of my friends reported that port 80 is working better), check different configuration and let us know if you made it work.

**Comment by Azaaaad** [comment]
I used port 80 and 443, but the same problem. Connection is OK about 1 hour, but after this period of time can't connect to proxy!

**Comment by VahidPY** [comment]
@Azaaaad Blocking IPs not the same on all ISPs. According your DSL ISP, if you can connect to your server through ssh, your IP is not blocked. Check all possibilities you guess might related. If you can ping your server (with the IP) inside of the country your IP, again it is not blocked. Check your service status using `service mtproto-proxy status`, but if just on one ISP not works, it's not the problem and your service is active. I used some other ports that solved my problem, you should also give it a try.

Also read all comments of [#79](https://github.com/TelegramMessenger/MTProxy/issues/79) and [#87](https://github.com/TelegramMessenger/MTProxy/issues/87)

**Comment by Azaaaad** [comment]
Thank you @VahidPY . I can connect to my VPS without any problem. I also get a ping of my ip, Its OK. Im completely confused whats happening!

**Comment by VahidPY** [comment]
Did you check out status of your mtproto proxy? Is everything ok?
Something similar happened to https://github.com/TelegramMessenger/MTProxy/issues/87#issuecomment-395405445 when his other services works so IP is not blocked. You have the same problem.

Please follow and participate in the issue #87.

**Comment by aminghaseminia** [comment]
@Azaaaad is absoloutely right. Most of mtproto proxies that I make don't work on DSL connections ONLY on android. the same proxy with the same ip and port works on PC with the same DSL connection. but on android the same proxy with the same IP and port doesn't work on the same DSL connection.
It's strange and it CAN'T be related to the connection. seems that there's something wrong with the android client. what can we do? 
P.s: not all proxies are like this, but the proxies that I make using the official mtproto proxy maker is like this.
