### ISSUE TITLE
how I can make the MTproxy ?

### ISSUE THREAD

**Issue by pesarbaadab** [TelegramMessenger/MTProxy#88]

**Comment by Kolahzary** [comment]
Follow instructions in Readme file
https://github.com/TelegramMessenger/MTProxy/blob/master/README

by the way you'll need a VPS server

**Comment by pesarbaadab** [comment]
thnks
If i want the Free VPS server , its there ?or not ?

**Comment by an-ivannikov** [comment]
Look in my repository. I tried to simplify and automate everything
https://github.com/an-ivannikov/mtproto-proxy-server
