### ISSUE TITLE
Limit 1 user per secret

### ISSUE THREAD

**Issue by Kolahzary** [TelegramMessenger/MTProxy#89]
Hello,
Is it possible to write a code that doesn't allow more than 1 user per each secret to connect to the proxy?
right now secrets are almost useless! why should someone add multiple secrets to a proxy server?

**Comment by ingria** [comment]
You can use socks for more granular access control.

**Comment by Kolahzary** [comment]
@ingria 
Unfortunately I.R.Iran's DPI firewalls can detect and block socks traffic easily.

**Comment by stek29** [comment]
That's a really, really bad idea.
Due to how secrets are used, having many of them would require trying to decrypt every incoming packet with all possible secrets to find one which is used. It's insane.

**Comment by kotovalexarian** [comment]
> Due to how secrets are used, having many of them would require trying to decrypt every incoming packet with all possible secrets to find one which is used. It's insane.

Why not just decrypt the first packet of an established connection?

We really need this feature to not allow proxy users to share their secrets without limits.

**Comment by amintado** [comment]
I have programmed limited server
One proxy secret for one user on 4core cpu vps with 6gig ddr4 ram
Now 1200 private users are using this mtproxy and it is working fine.
If you have this source i can give you that 
Contact with me for sale
