### ISSUE TITLE
Set start up

### ISSUE THREAD

**Issue by RexProg** [TelegramMessenger/MTProxy#90]
How can i set mtproto-proxy start up?
OS : Ubuntu 16

**Comment by an-ivannikov** [comment]
installing as service in systemctl

**Comment by RexProg** [comment]
Excuse me
How can i install as service in systemctl?

**Comment by an-ivannikov** [comment]
Look at the example I have

https://github.com/an-ivannikov/mtproto-proxy-server/blob/master/scripts/mtproto-proxy-install-service.sh

**Comment by an-ivannikov** [comment]
Or just install my mtproto-proxy-server as specified in my instructions

**Comment by loskiq** [comment]
@RexProg Example: http://p.ip.fi/lYVo

**Comment by stek29** [comment]
See readme
