### ISSUE TITLE
Using different IPs

### ISSUE THREAD

**Issue by ICQFan4ever** [TelegramMessenger/MTProxy#91]
I have 15 additional IP-addresses on my server, every one is listed on virtual interface, such as ens3:1, ens3:2 etc...
How should I run MTProxy to enable feature when external IP == IP where connect was established, for example, default ip is 1.1.1.2 , additional ip is 2.2.2.2, when user is connected to 1.1.1.2 - traffic comes outside from 1.1.1.2, when connected through 2.2.2.2 - it goes via 2.2.2.2

**Comment by Shazoo** [comment]
iptables ？

**Comment by seega** [comment]
**https://github.com/TelegramMessenger/MTProxy/issues/66#issuecomment-394179655**

**Comment by ICQFan4ever** [comment]
@seega thanks. I will punish myself for non-using-searching and ignoring existins issues
