### ISSUE TITLE
Insane RAM usage

### ISSUE THREAD

**Issue by giuseppeM99** [TelegramMessenger/MTProxy#92]
The RAM usage of the proxy is insane is this chrome?

![image](https://user-images.githubusercontent.com/8383704/41036349-0d0108c4-6990-11e8-89d8-7e93f254ab43.png)

**Comment by temporaryaccount** [comment]
Where do you see "insane" usage? The VIRT column says nothing. Those are threads, in reality there are just two processes in this image. One has 45KB resources allocated, while the other 33KB.

**Comment by stek29** [comment]
Many apps allocate big chunks of virtual memory, but use only parts of it -- go runtime does that, for example.
