### ISSUE TITLE
Load Balancing 

### ISSUE THREAD

**Issue by RexProg** [TelegramMessenger/MTProxy#93]
How to load balancing mtproto servers?

**Comment by temporaryaccount** [comment]
Most likely using [HAProxy](https://www.haproxy.org/) or [Nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/).

**Comment by Kolahzary** [comment]
I tried NGINX with following configuration and it worked like a charm ^_^
`
stream {
       upstream tgproxy_backend {
               server [ip-addr-of-first-server]:[port];
               server [ip-addr-of-another-server]:[port];
       }
       server {
               listen [front-port];
               proxy_pass tgproxy_backend;
       }
}`

**Comment by seega** [comment]
@temporaryaccount I would not advise, an extra server whose channel will limit the speed of all other proxies. Round-Robin DNS - practical and works without problems.

**Comment by stek29** [comment]
you can also make a load balancer with iptables and nat
