### ISSUE TITLE
Add index page with tg://proxy link on 80 port

### ISSUE THREAD

**Issue by t1maccapp** [TelegramMessenger/MTProxy#94]
It looks like it is really hard to share proxy settings outside of telegram. It would be really cool if I could just run proxy and send ip address of host to other people who does not have an access to https://t.me.

**Comment by S0m3Th1nG-AwFul** [comment]
Use tg://proxy?server=SERVER_ADDRESS&port=PORT_NUMBER&secret=YOUR_SECRET instead.

**Comment by t1maccapp** [comment]
@S0m3Th1nG-AwFul I mean this link does not work in these cases:
1. Sending _tg://proxy_ to VK.com, others cannot just tap on it and add new proxy.
2. Sending _tg://proxy_ link via email service like SendGrid, it allows only http links.
3. Copy-pasting _tg://proxy_ link to a browser address bar, it does not work this way.

Instead, I had to create html page which redirects users to _tg://proxy_ link and send them http://ip.address:80. So all receivers are able to add new proxy from different sources **in one click**.

So my point is that adding a simple index page to a proxy host by default will simplify the process of distributing proxies via other communicating channels.

**Comment by Kolahzary** [comment]
It's not a good idea for two reasons:
1. It'll make it really easy for governments to discover mtproto proxy servers.
2. Many servers have port 80 already used by a web server!

By the way you can easily install a web server on your own server and create a simple html page which contains your tg://proxy links! why should it be a feature of the mtproto proxy server itself?

**Comment by an-ivannikov** [comment]
Use my package, there is a simple server at http://domain.name:80/
https://github.com/an-ivannikov/mtproto-proxy-server

**Comment by stek29** [comment]
You can make a simple static web server linking to tg://, it's not that hard.
I doubt it makes sense to have it in the proxy.

**Comment by t1maccapp** [comment]
Ok, it was just a feature suggestion. There is no problem with setting web server manually.
