### ISSUE TITLE
Are internal proxy lists does not updated in applications?

### ISSUE THREAD

**Issue by Katarn** [TelegramMessenger/MTProxy#97]
I did not find the answer to this question in the FAQ.

I set up mtproxy on my server, registered it in `@MTProxybot`. As the statistics showed, for a week, except for me, nobody used this proxy. It means that the proxy is personal. I wanted to share it to all Telegram users who are experiencing problems due to blocking access to Telegram servers, but it means that for this I have to deal with the distribution of the link to the proxy, and from this there are three problems:

1. The link appears in the public access, the RKN can easily use a crawler to collect it.
2. The link should be distributed on every possible of Internet resources, this requires a lot of effort.
3. Telegram company still has to constantly update the list of its own proxies for transparent use by the application.

Do I understand the current situation correctly?

**Comment by stek29** [comment]
See #14
