### ISSUE TITLE
How config This for windows server ?

### ISSUE THREAD

**Issue by hafiz8** [TelegramMessenger/MTProxy#98]
Hi 
i have RDP  windows server 2008
How config mtproxy  for add sponser chanel?

**Comment by Kolahzary** [comment]
[Install docker-compose](https://docs.docker.com/compose/install/) on your OS first.

Then use either [Original Docker Image](https://github.com/iShift/docker-compose-mtproxy) or [Unlocked Docker Image](https://github.com/Kolahzary/docker-compose-mtproxy).

**Comment by stek29** [comment]
#5
